import type { ArticleDocument } from '../types';

export const assistantComparison = {
  id: 'dce-02-chatgpt-claude-gemini',
  title: 'ChatGPT vs Claude vs Gemini: Which One Should a Solo Business Pay For?',
  slug: '/comparisons/claude-vs-chatgpt-vs-gemini-2026',
  description: 'Compare ChatGPT, Claude and Gemini for writing, files, research and connected work. Decide whether one paid AI subscription fits your business.',
  excerpt: 'ChatGPT, Claude and Gemini overlap more than their marketing suggests. Compare the free and roughly $20 plans by tasks, limits, integrations and total value.',
  deck: 'ChatGPT, Claude and Gemini overlap more than their marketing suggests. Compare the free and roughly $20 plans by tasks, limits, integrations and total value.',
  seoTitle: 'ChatGPT vs Claude vs Gemini for Solo Businesses | Domsky',
  socialTitle: 'ChatGPT vs Claude vs Gemini: Which One Fits a Solo Business?',
  socialDescription: 'A practical comparison of plans, limits, integrations and upgrade triggers—without a universal winner.',
  category: 'Comparisons',
  author: { name: 'Domsky Solutions editorial', type: 'Organization', url: '/about' },
  publishedAt: '2026-09-23',
  updatedAt: '2026-09-23',
  verifiedAt: '2026-09-23',
  status: 'published',
  contentType: 'comparison',
  tags: ['ChatGPT', 'Claude', 'Gemini', 'AI assistants', 'Solo business'],
  relatedSlugs: ['/comparisons/chatgpt-astra-vs-alternatives', '/blog/replaced-saas-stack-with-ai-tools'],
  readingMinutes: 13,
  featuredImageRequired: true,
  featuredImage: {
    src: '/images/claude-vs-chatgpt-vs-gemini-2026.jpg',
    alt: 'Claude, ChatGPT and Gemini shown in a 2026 AI comparison cover graphic.',
    caption: 'Cover graphic supplied by Domsky. The article does not claim a universal performance winner.',
    width: 1376,
    height: 768,
  },
  ogImage: {
    src: '/images/claude-vs-chatgpt-vs-gemini-2026.jpg',
    alt: 'Claude, ChatGPT and Gemini shown in a 2026 AI comparison cover graphic.',
    width: 1376,
    height: 768,
  },
  commercial: true,
  recommendedUpdateDays: 30,
  affiliateDisclosureRequired: false,
  disclosure: 'No provider paid for placement. Product and source links in this comparison are direct, non-affiliate links. Recommendations remain editorially independent.',
  verificationPending: [],
  sources: [
    { id: 'oai-01', title: 'OpenAI: ChatGPT pricing', url: 'https://chatgpt.com/pricing/' },
    { id: 'oai-02', title: 'OpenAI: What is ChatGPT Plus?', url: 'https://help.openai.com/en/articles/6950777-what-is-chatgpt-plus' },
    { id: 'oai-03', title: 'OpenAI: ChatGPT Free Tier FAQ', url: 'https://help.openai.com/en/articles/9275245-chatgpt-free-tier-faq' },
    { id: 'oai-04', title: 'OpenAI: How data is used to improve model performance', url: 'https://openai.com/policies/how-your-data-is-used-to-improve-model-performance/' },
    { id: 'ant-01', title: 'Anthropic: Claude pricing', url: 'https://claude.com/pricing' },
    { id: 'ant-02', title: 'Anthropic: How usage and length limits work', url: 'https://support.claude.com/en/articles/11647753-how-do-usage-and-length-limits-work' },
    { id: 'ant-03', title: 'Anthropic: Why Claude API and paid subscriptions are separate', url: 'https://support.claude.com/en/articles/9876003-i-have-a-paid-claude-subscription-pro-max-team-or-enterprise-plans-why-do-i-have-to-pay-separately-to-use-the-claude-api-and-console' },
    { id: 'ant-04', title: 'Anthropic: Is consumer data used for model training?', url: 'https://privacy.anthropic.com/en/articles/10023580-is-my-data-used-for-model-training' },
    { id: 'goo-01', title: 'Google: Google AI plans', url: 'https://one.google.com/about/google-ai-plans/' },
    { id: 'goo-02', title: 'Google: Gemini Apps limits and upgrades', url: 'https://support.google.com/gemini/answer/16275805?hl=en' },
    { id: 'goo-03', title: 'Google: Use Deep Research in Gemini Apps', url: 'https://support.google.com/gemini/answer/15719111?hl=en' },
    { id: 'goo-04', title: 'Google: Connect Google Workspace to Gemini Apps', url: 'https://support.google.com/gemini/answer/15229592?hl=en' },
    { id: 'goo-05', title: 'Google: Gemini Apps Privacy Hub', url: 'https://support.google.com/gemini/answer/13594961?hl=en' },
    { id: 'goo-06', title: 'Google: Google AI plans and Gemini API', url: 'https://ai.google.dev/gemini-api/docs/google-ai-plans' },
    { id: 'nist-01', title: 'NIST: Artificial Intelligence Risk Management Framework — Generative Artificial Intelligence Profile', url: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence' },
  ],
  blocks: [
    {
      type: 'note',
      title: 'Evidence basis',
      text: [
        'This is a documentation-based comparison, researched on 23 September 2026. Domsky did not run a controlled head-to-head product test for this article. Product capabilities and prices come from current provider documentation. The recommendations are Domsky’s editorial analysis of those documented differences. ',
        { text: 'Read the review methodology', href: '/methodology' },
        '.',
      ],
    },
    { type: 'heading', level: 2, id: 'short-answer', text: 'The short answer' },
    {
      type: 'quickAnswer',
      title: 'Start free, then pay for one assistant',
      text: 'Pay only when a recurring task is blocked by a limit or a paid feature that saves you from another subscription. Choose ChatGPT for broad tool coverage, Claude for its document, project and included coding workflow, or Gemini when the Google bundle and Google-app integration have real value.',
    },
    { type: 'paragraph', text: 'If you run a solo business, you probably do not need three paid AI assistants.' },
    {
      type: 'paragraph',
      text: [
        'Start with the free version of the assistant you already use. At the current US monthly prices, the practical decision is usually between ',
        { text: 'ChatGPT Plus at $20', href: 'https://help.openai.com/en/articles/6950777-what-is-chatgpt-plus' },
        ', ',
        { text: 'Claude Pro at $20', href: 'https://claude.com/pricing' },
        ', and ',
        { text: 'Google AI Pro at $19.99', href: 'https://one.google.com/about/google-ai-plans/' },
        '. Prices, taxes, eligibility and availability vary by country.',
      ],
    },
    {
      type: 'list',
      items: [
        [{ text: 'Choose ChatGPT Plus', strong: true }, ' when you want broad general-purpose tools in one place: writing, files, data analysis, research, images, projects and connected apps.'],
        [{ text: 'Choose Claude Pro', strong: true }, ' when its Projects, Research, document creation, Claude Code or Microsoft 365/Chrome workflow matches work you already do.'],
        [{ text: 'Choose Google AI Pro', strong: true }, ' when Gemini inside Gmail, Docs and Sheets, plus the included Google storage and other bundle benefits, replace costs or friction you already have.'],
        [{ text: 'Stay free', strong: true }, ' when you are still experimenting or rarely hit a useful limit.'],
      ],
    },
    { type: 'note', title: 'Fit, not a universal winner', text: 'These are fit-based recommendations. They are not claims that one model always writes, reasons or researches better.' },
    { type: 'heading', level: 2, id: 'paid-plan-comparison', text: 'Compare the paid plans at the practical decision point' },
    { type: 'paragraph', text: 'The table below uses provider documentation, not a Domsky benchmark.' },
    {
      type: 'pricing',
      caption: 'Documented plan differences at the practical decision point',
      columns: ['Decision factor', 'ChatGPT', 'Claude', 'Gemini'],
      rows: [
        ['Free starting point', 'Unlimited everyday text chats subject to safeguards; several tools have separate limited access', 'Chat, web search, file creation/code execution, memory, connectors and Artifacts; usage limits apply', 'Standard access to Gemini; limits depend on the model and feature'],
        ['Main individual paid plan compared', 'ChatGPT Plus', 'Claude Pro', 'Google AI Pro'],
        ['Current US price', '$20/month, monthly billing', '$20/month, or $200 billed upfront annually', '$19.99/month, or $199.99/year'],
        ['What the paid plan mainly changes', 'Advanced models and expanded messages, files, deep research, memory, projects, tasks, custom GPTs, Codex and Work', 'More usage plus Research, Projects, Claude Code, document/slide creation, scheduled tasks, Chrome and Microsoft 365 access', 'Four times standard Gemini access, expanded Pro/Deep Research access, Gemini in Google apps and a broader Google bundle'],
        ['Limits', 'Limits vary by feature and system conditions', 'Rolling five-hour session limits plus weekly limits; usage depends on model, conversation and feature', 'Compute-based; prompt complexity, model, feature and chat length affect consumption'],
        ['API included?', 'No; billed separately', 'No; Console/API billed separately', 'Direct Gemini API use is billed and managed separately'],
        ['Best reason to pay', 'You repeatedly use several of its included tools', 'Its paid workflow matches document, coding or connected-work needs', 'The Google integration and bundle have value beyond the chat itself'],
      ],
    },
    { type: 'paragraph', text: [{ text: 'Official claims: ', strong: true }, 'The prices, plan inclusions and limit descriptions above are taken from OpenAI, Anthropic and Google documentation listed in the source section.'] },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Because the prices are almost identical at this level, choosing by a headline model name is less useful than choosing by your recurring work and existing subscriptions.'] },
    { type: 'heading', level: 2, id: 'shared-capabilities', text: 'What all three can do' },
    { type: 'paragraph', text: 'All three can help with common solo-business tasks such as:' },
    { type: 'list', items: ['revising an email;', 'outlining an article;', 'summarizing a document;', 'brainstorming options;', 'researching a topic with web sources;', 'turning notes into a first draft.'] },
    { type: 'paragraph', text: 'That overlap matters. If the free assistant you already use completes these jobs and you rarely hit a limit, switching products or adding a paid plan may create more setup than value.' },
    { type: 'paragraph', text: 'The overlap also explains why broad claims such as “best for writing” age badly. Results depend on the exact prompt, model, plan, files, web access and review standard. Domsky has not run a controlled current test that would justify that verdict.' },
    {
      type: 'paragraph',
      text: [
        { text: 'NIST identifies confabulation', href: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence' },
        '—confidently presented false content—as a distinct generative-AI risk. Treat every assistant as a drafting and analysis tool whose factual outputs still need checking.',
      ],
    },
    { type: 'heading', level: 2, id: 'chatgpt', text: 'When ChatGPT is the practical choice' },
    { type: 'paragraph', text: [{ text: 'OpenAI’s current plan table', href: 'https://chatgpt.com/pricing/' }, ' positions ChatGPT Plus as a broad productivity subscription. It expands messages and uploads, deep research, memory and context, and adds projects, scheduled tasks, custom GPTs, expanded Codex use and broader ChatGPT Work access.'] },
    { type: 'paragraph', text: 'That breadth can make ChatGPT the practical choice if you regularly move among several kinds of work:' },
    { type: 'list', items: ['reviewing a spreadsheet;', 'researching a question;', 'creating or editing an image;', 'organizing a project;', 'drafting content;', 'doing a small supervised coding task.'] },
    { type: 'paragraph', text: 'The reason to choose it is the range of tools you will actually use, not a promise that every answer will be better.' },
    { type: 'paragraph', text: 'ChatGPT Free remains a reasonable place to begin. OpenAI currently describes everyday text chats as unlimited subject to safeguards, while uploads, data analysis, image creation and other tools have separate limits. Upgrade when one of those limits interrupts real work often enough to justify $20—not because the paid label looks more professional.' },
    { type: 'heading', level: 2, id: 'claude', text: 'When Claude is the practical choice' },
    { type: 'paragraph', text: [{ text: 'Anthropic’s current plan table', href: 'https://claude.com/pricing' }, ' says Claude Free includes web search, file creation, code execution, memory, connectors and Artifacts. Claude Pro adds more usage, Research, Projects, Claude Code, document/slide creation, scheduled tasks, Claude in Chrome and Microsoft 365 access.'] },
    { type: 'paragraph', text: 'Claude Pro is therefore a sensible candidate when one of those paid workflows is central to your week. Examples include maintaining a long-running project with reference material, creating editable office files, or using Claude Code for supervised development work.' },
    { type: 'paragraph', text: ['Claude’s limits require care. ', { text: 'Anthropic says', href: 'https://support.claude.com/en/articles/11647753-how-do-usage-and-length-limits-work' }, ' usage depends on conversation length and complexity, the chosen model and the features used. Limits reset on a rolling five-hour session window, and paid plans also have weekly limits. Claude Code and regular Claude use draw from the same plan pool. A fixed “messages per day” promise would be misleading.'] },
    { type: 'paragraph', text: 'Choose Claude because its product workflow fits, not because an article declares its prose universally better. That claim would need a current matched test that this article does not have.' },
    { type: 'heading', level: 2, id: 'gemini', text: 'When Gemini is the practical choice' },
    { type: 'paragraph', text: ['Google AI Pro is more than a chatbot subscription. ', { text: 'Google currently lists', href: 'https://one.google.com/about/google-ai-plans/' }, ' 5 TB of storage, four times standard Gemini access, expanded access to Gemini Pro and Deep Research, and Gemini features in Gmail, Docs and Sheets. The US plan also includes other benefits whose availability varies by country.'] },
    { type: 'paragraph', text: 'This bundle can be the strongest reason to choose Gemini. If you already work in Google apps and would otherwise pay for storage or another included benefit, the subscription may replace a real cost or reduce switching between tools.' },
    { type: 'paragraph', text: 'Do not assume every advertised Google benefit is available in every account or region. Google marks some features as US-only, and personal Google AI plans differ from Workspace business accounts. Google also states that users of Google AI plans in the EEA, Switzerland and the UK must be 18 or older. Confirm the exact account, eligibility, country and feature before buying.' },
    { type: 'paragraph', text: [{ text: 'Google describes Gemini limits', href: 'https://support.google.com/gemini/answer/16275805?hl=en' }, ' as compute-based. Complex prompts and heavier features can use more of the allowance, and limits can change. This is another reason to avoid a fixed message-count comparison.'] },
    { type: 'heading', level: 2, id: 'upgrade-trigger', text: 'Free or paid: use a real upgrade trigger' },
    { type: 'paragraph', text: 'A paid plan should remove a repeated constraint. Useful upgrade triggers include:' },
    { type: 'list', ordered: true, items: ['You hit a file, research or model limit during paid work more than once.', 'A paid integration removes a repeated copy-and-paste step.', 'A paid feature replaces another subscription you can actually cancel.', 'You need a project, coding or document workflow that the free plan does not provide.', 'Waiting for a limit to reset costs more than the monthly fee in delayed work.'] },
    { type: 'paragraph', text: 'Weak upgrade reasons include curiosity, fear of missing out, or a benchmark score unrelated to your tasks.' },
    { type: 'paragraph', text: 'Use the free plan for at least three real tasks first. If it works, keep it. If it fails, record exactly why: limit, missing integration, weak output after revision, or too much review. That evidence tells you what a paid plan needs to fix.' },
    { type: 'heading', level: 2, id: 'api-billing', text: 'Do not confuse a chat subscription with API billing' },
    { type: 'paragraph', text: 'A ChatGPT, Claude or Google AI subscription pays for the provider’s consumer application and included features. It does not automatically cover API use in an external app or automation.' },
    { type: 'paragraph', text: [{ text: 'OpenAI', href: 'https://help.openai.com/en/articles/6950777-what-is-chatgpt-plus' }, ', ', { text: 'Anthropic', href: 'https://support.claude.com/en/articles/9876003-i-have-a-paid-claude-subscription-pro-max-team-or-enterprise-plans-why-do-i-have-to-pay-separately-to-use-the-claude-api-and-console' }, ' and ', { text: 'Google', href: 'https://ai.google.dev/gemini-api/docs/google-ai-plans' }, ' each document consumer subscriptions and direct API billing separately.'] },
    { type: 'paragraph', text: 'This matters when a tutorial asks you to add an API key. At that point, check the API’s own pricing, limits and security requirements. Do not assume your $20 chat subscription covers it.' },
    { type: 'heading', level: 2, id: 'privacy', text: 'Privacy and client data need a separate decision' },
    { type: 'paragraph', text: 'A useful feature is not automatically suitable for confidential information.' },
    { type: 'paragraph', text: [{ text: 'OpenAI', href: 'https://openai.com/policies/how-your-data-is-used-to-improve-model-performance/' }, ' provides an opt-out and temporary chats for consumer use. ', { text: 'Anthropic', href: 'https://privacy.anthropic.com/en/articles/10023580-is-my-data-used-for-model-training' }, ' says consumer chats and coding sessions may be used to improve Claude if the user chooses to allow it. ', { text: 'Google', href: 'https://support.google.com/gemini/answer/13594961?hl=en' }, ' says a subset of Gemini consumer chats may be reviewed when Keep Activity is on, and provides temporary chats and activity controls.'] },
    { type: 'paragraph', text: 'Those summaries are not a complete privacy assessment. Consumer plans, business plans and API products can have different terms. Connected apps also require permissions to access information in services such as email or cloud storage.' },
    { type: 'paragraph', text: 'Before using any assistant with client or business data:' },
    { type: 'list', items: ['review the current setting and product terms;', 'remove unnecessary personal or confidential details;', 'connect only the apps needed for the task;', 'check whether your client agreement allows the processing;', 'use a suitable business product when administration, retention or contractual controls are required.'] },
    { type: 'heading', level: 2, id: 'three-task-trial', text: 'A simple three-task trial before you subscribe' },
    { type: 'paragraph', text: 'Use the same real tasks with the free options. Do not upload confidential material.' },
    { type: 'heading', level: 3, id: 'email-trial', text: '1. Revise a real email' },
    { type: 'paragraph', text: 'Give each assistant the same draft, audience, purpose and tone. Ask it to preserve facts and list any assumptions. Check whether the revision is accurate, specific and still sounds like you.' },
    { type: 'heading', level: 3, id: 'document-trial', text: '2. Work with a document you are allowed to upload' },
    { type: 'paragraph', text: 'Use a public or nonsensitive brief. Ask for a summary, missing decisions and a short action list. Check the output against the document. Record how much correction was needed.' },
    { type: 'heading', level: 3, id: 'research-trial', text: '3. Research a decision using cited sources' },
    { type: 'paragraph', text: 'Ask a narrow current question. Require direct source links, publication dates and a separate uncertainty section. Open the cited pages and verify the important facts yourself.' },
    {
      type: 'table',
      caption: 'Reader-run trial scorecard',
      columns: ['Check', 'Result to record'],
      rows: [
        ['Completed the task', 'Yes / partly / no'],
        ['Factual corrections needed', 'Count and describe'],
        ['Useful source links', 'Yes / partly / no'],
        ['Review effort', 'Rough minutes, measured during your trial'],
        ['Limit reached', 'Which limit and when'],
        ['Missing paid feature', 'Exact feature, not a general feeling'],
      ],
    },
    { type: 'paragraph', text: 'This is a reader-run trial, not a Domsky test result. Its value is that it measures your work.' },
    { type: 'cta', title: 'Try the three-task checklist', text: 'Use the assistant you already have and record what actually blocks your work before paying.', label: 'Start with the first task', href: '#email-trial' },
    { type: 'heading', level: 2, id: 'recommendation', text: 'Domsky recommendation by situation' },
    {
      type: 'table',
      caption: 'Conditional recommendation by situation',
      columns: ['Your situation', 'Starting choice', 'Reason'],
      rows: [
        ['Tasks are occasional and the free allowance is enough', 'Stay free', 'This is the default starting recommendation.'],
        ['You will use several tools for files, research, images, projects, data work and occasional coding', 'ChatGPT Plus', 'Its broad workspace fits several recurring kinds of work.'],
        ['Projects, Research, editable documents or slides, Claude Code, or Microsoft 365/Chrome support recurring work', 'Claude Pro', 'Its paid workflow matches the work you already do.'],
        ['Gmail, Docs and Sheets integration, Google storage and other bundle benefits have clear value', 'Google AI Pro', 'The Google ecosystem and bundle reduce real cost or friction.'],
      ],
    },
    { type: 'paragraph', text: 'Do not pay for two general assistants yet unless the second one completes a recurring job the first cannot, and that difference is worth another subscription. Similar features are not proof of incremental value.' },
    { type: 'paragraph', text: ['If another subscription may be redundant, use the ', { text: 'software stack audit worksheet', href: '/blog/replaced-saas-stack-with-ai-tools' }, ' to test job coverage, recurring cash and migration risk before cancelling it.'] },
    { type: 'paragraph', text: 'If two options satisfy your requirements, keep the one you already know. Switching has a cost too: settings, saved context, connected apps and new habits.' },
    { type: 'heading', level: 2, id: 'questions', text: 'Common questions' },
    { type: 'heading', level: 3, id: 'free-enough', text: 'Is a free AI assistant enough for a solo business?' },
    { type: 'paragraph', text: 'Often, yes. A free plan can cover occasional drafting, summarizing and brainstorming. Upgrade after a recurring limit or missing capability appears in real work.' },
    { type: 'heading', level: 3, id: 'workspace', text: 'Which assistant is best for Google Workspace?' },
    { type: 'paragraph', text: 'Google AI Pro has the clearest bundle for someone already working in Gmail, Docs and Sheets. Claude and ChatGPT also offer connected-app or extension workflows, but exact access varies by plan and account. Verify the specific integration you need.' },
    { type: 'heading', level: 3, id: 'coding-tool', text: 'Which paid plan includes a coding tool?' },
    { type: 'paragraph', text: ['ChatGPT Plus includes expanded Codex usage, while Claude Pro includes Claude Code. This article does not compare their coding performance. ', { text: 'Compare supervised coding workflows', href: '/comparisons/chatgpt-astra-vs-alternatives' }, ' in Domsky’s separate 2026 guide.'] },
    { type: 'heading', level: 3, id: 'api-included', text: 'Does a paid chat plan include API usage?' },
    { type: 'paragraph', text: 'No. The providers document consumer chat subscriptions and API billing separately.' },
    { type: 'heading', level: 3, id: 'research-tool', text: 'Should I also pay for a dedicated research tool?' },
    { type: 'paragraph', text: 'Only if source-first research is a frequent task and the assistant you already pay for does not meet your needs. Test its included search or research mode first, then compare the additional tool against a defined gap.' },
    { type: 'heading', level: 3, id: 'two-assistants', text: 'Should a solo business pay for two assistants?' },
    { type: 'paragraph', text: 'Usually, no. Add a second paid general assistant only after it repeatedly completes a valuable job your first choice cannot.' },
    { type: 'paragraph', text: ['This comparison was checked against current provider pricing, help and privacy documentation on 23 September 2026. NIST guidance supports the general need to verify generated facts. No provider paid for placement, and no head-to-head Domsky product test is claimed. ', { text: 'See how Domsky evaluates evidence', href: '/methodology' }, '.'] },
    { type: 'paragraph', text: 'Prices and features change quickly. Confirm the checkout price, tax, account eligibility and plan details before subscribing.' },
    { type: 'sources', id: 'sources', title: 'Sources & methodology' },
  ],
} satisfies ArticleDocument;
