import type { ArticleDocument } from '../types';
import { PUBLIC_AUTHOR } from '../../data/site';

export const kitReview = {
  id: 'dce-04-kit-review',
  title: 'Kit Review for a Solo Creator: Free-Plan Limits, Welcome Emails and Upgrade Triggers',
  slug: '/reviews/convertkit',
  description: 'A practical Kit review for solo creators: what the Free plan includes, how lead magnets and welcome emails work, and when Creator is worth paying for.',
  excerpt: 'Kit Free includes one email sequence and one basic visual automation. See where Creator becomes necessary for unlimited or advanced workflows.',
  deck: 'Define the email workflow, use the included sequence deliberately, and upgrade only when advanced automation becomes necessary.',
  seoTitle: 'Kit Review for Solo Creators: Free Plan & Limits | Domsky',
  socialTitle: 'Kit Free or Creator? A Practical Solo-Creator Review',
  socialDescription: 'See what Kit Free can handle, where advanced automation becomes paid, and what to test before moving your list.',
  category: 'Email Marketing',
  author: PUBLIC_AUTHOR,
  publishedAt: '2026-09-25',
  updatedAt: '2026-09-25',
  verifiedAt: '2026-09-24',
  status: 'published',
  contentType: 'review',
  tags: ['Kit', 'ConvertKit', 'Email marketing', 'Lead magnets', 'Solo creators'],
  relatedSlugs: ['/uses', '/comparisons/kit-vs-mailerlite-vs-beehiiv'],
  readingMinutes: 13,
  featuredImageRequired: true,
  featuredImage: {
    src: '/images/kit-free-vs-creator-workflow.svg',
    alt: 'Kit Free and Creator email workflows compared from signup to welcome sequence.',
    caption: 'Editorial workflow illustration. Product limits are based on Kit documentation checked 24 September 2026.',
    width: 1600,
    height: 900,
  },
  ogImage: {
    src: '/images/kit-free-vs-creator-workflow.svg',
    alt: 'Kit Free and Creator email workflows compared from signup to welcome sequence.',
    width: 1600,
    height: 900,
  },
  commercial: true,
  recommendedUpdateDays: 30,
  affiliateDisclosureRequired: false,
  disclosure: 'No monetized Kit link is included. Product links are direct, non-affiliate sources, and plan recommendations remain editorially independent.',
  verificationPending: [],
  sources: [
    { id: 'kit-01', title: 'Kit: Pricing and plans', url: 'https://kit.com/pricing' },
    { id: 'kit-02', title: 'Kit Help Center: The Kit Free plan', url: 'https://help.kit.com/en/articles/16627071-the-kit-free-plan' },
    { id: 'kit-02b', title: 'Kit Help Center: Visual Automations on the Newsletter Plan', url: 'https://help.kit.com/en/articles/9053626-visual-automations-on-the-newsletter-plan' },
    { id: 'kit-03', title: 'Kit Help Center: Creator vs Pro — choose the right plan', url: 'https://help.kit.com/en/articles/4494683-creator-vs-pro-choose-the-right-plan' },
    { id: 'kit-04', title: 'Kit: Features', url: 'https://kit.com/features' },
    { id: 'kit-05', title: 'Kit Help Center: The Confirmation Email', url: 'https://help.kit.com/en/articles/2502655-the-confirmation-email' },
    { id: 'kit-06', title: 'Kit Help Center: The all-important double opt-in', url: 'https://help.kit.com/en/articles/2971364-the-all-important-double-opt-in' },
    { id: 'kit-07', title: 'Kit Help Center: Grow your list with content upgrades', url: 'https://help.kit.com/en/articles/2502644-grow-your-list-with-content-upgrades' },
    { id: 'kit-08', title: 'Kit Help Center: Creating and sending an Email Sequence', url: 'https://help.kit.com/en/articles/2502629-creating-and-sending-an-email-sequence-in-kit' },
    { id: 'kit-09', title: 'Kit Help Center: How to use Kit Visual Automations', url: 'https://help.kit.com/en/articles/2502666-how-to-use-kit-visual-automations' },
    { id: 'kit-10', title: 'Kit Help Center: Visual Automations actions', url: 'https://help.kit.com/en/articles/2502537-visual-automations-actions' },
    { id: 'kit-11', title: 'Kit Help Center: Subscriber profile page and status', url: 'https://help.kit.com/en/articles/2502651-the-subscriber-profile-page-and-status' },
    { id: 'kit-12', title: 'Kit Help Center: How to remove subscribers', url: 'https://help.kit.com/en/articles/2502654-how-to-remove-subscribers-from-your-email-list' },
    { id: 'kit-13', title: 'Kit Help Center: How to export subscribers', url: 'https://help.kit.com/en/articles/2502489-how-to-export-subscribers-in-kit' },
    { id: 'kit-14', title: 'Kit Help Center: Apps and integrations overview', url: 'https://help.kit.com/en/articles/9427509-apps-and-integrations-overview' },
    { id: 'kit-15', title: 'Kit Help Center: Kit API overview', url: 'https://help.kit.com/en/articles/9902901-kit-api-overview' },
    { id: 'kit-16', title: 'Kit: Affiliate Program', url: 'https://kit.com/affiliate' },
  ],
  blocks: [
    {
      type: 'note',
      title: 'Documentation-based review',
      text: [
        'This review uses Kit’s pricing page and help center as checked on 24 September 2026. Domsky has not completed the signup-to-unsubscribe product test described below. Product capabilities are attributed to Kit; plan recommendations are Domsky editorial analysis. ',
        { text: 'See how Domsky verifies software claims', href: '/methodology' },
        '.',
      ],
    },
    { type: 'heading', level: 2, id: 'short-answer', text: 'The short answer' },
    {
      type: 'quickVerdict',
      label: 'At a glance',
      summary: 'Kit Free fits forms, landing pages, an incentive email, broadcasts, one Email Sequence and one basic action-only Visual Automation.',
      bestFor: 'Creators starting with one lead magnet, one audience and one fixed welcome sequence.',
      notFor: 'A workflow that requires multiple sequences, advanced branching, rules or several automation paths.',
      verdict: 'Start Free until a named workflow exceeds its one-sequence and basic-automation boundary.',
    },
    { type: 'paragraph', text: 'Kit—formerly ConvertKit—is a practical option for a creator who needs forms, landing pages, one-off newsletters and basic subscriber organization. Its Free plan currently supports up to 10,000 subscribers.' },
    { type: 'paragraph', text: 'The important limit is workflow depth. Kit’s current Newsletter Plan help article documents one Email Sequence and one basic action-only Visual Automation. Unlimited sequences, event and condition steps, rules and advanced automation require a paid plan.' },
    { type: 'paragraph', text: [{ text: 'Short recommendation: ', strong: true }, 'Start with Kit Free if one form, an incentive email, one fixed welcome sequence and broadcasts cover the workflow. Choose Creator when you need several sequences, branching or behavior-based follow-up.'] },
    { type: 'paragraph', text: ['No affiliate link is included in this review. Read the site’s ', { text: 'affiliate and editorial disclosure', href: '/disclaimer' }, ' for the policy that applies if a verified relationship is added later.'] },
    { type: 'heading', level: 2, id: 'free-plan', text: 'What Kit Free includes now' },
    { type: 'paragraph', text: 'Kit’s current pricing and Free-plan documentation list up to 10,000 email subscribers, unlimited forms and landing pages, unlimited broadcasts, tags and segments, digital products and subscriptions, broadcast A/B testing, free recommendations through the Creator Network and API access.' },
    { type: 'paragraph', text: [{ text: 'Broadcast: ', strong: true }, 'a one-off email sent at a chosen time. ', { text: 'Sequence: ', strong: true }, 'a set of automated emails a subscriber receives in order. Kit’s current Newsletter Plan documentation includes one sequence; paid plans add unlimited sequences.'] },
    {
      type: 'pricing',
      caption: 'Current documented plan boundaries',
      columns: ['Need', 'Free', 'Creator', 'Pro'],
      rows: [
        ['Forms and landing pages', 'Yes', 'Yes', 'Yes'],
        ['One-off email broadcasts', 'Yes', 'Yes', 'Yes'],
        ['Tags and segments', 'Yes', 'Yes', 'Yes'],
        ['Up to 10,000 subscribers', 'Yes', 'Paid tiers scale by list size', 'Paid tiers scale by list size'],
        ['Email sequences', 'One', 'Unlimited', 'Unlimited'],
        ['Visual automations', 'One basic action-only automation', 'Unlimited with advanced steps', 'Unlimited with advanced steps'],
        ['Rules and RSS campaigns', 'No under current Free documentation', 'Yes', 'Yes'],
        ['Advanced engagement and deliverability reporting', 'No', 'Limited compared with Pro', 'Yes'],
        ['Unlimited users', 'No', 'No', 'Yes'],
      ],
    },
    { type: 'paragraph', text: [{ text: 'Official claim: ', strong: true }, 'These boundaries come from Kit’s live pricing page and current Free-plan help article.'] },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Free can run one useful welcome path, but it is not an unlimited automation plan. The upgrade decision begins when the workflow exceeds that boundary.'] },
    { type: 'heading', level: 2, id: 'confirmation-vs-sequence', text: 'The important distinction: confirmation email versus welcome sequence' },
    { type: 'paragraph', text: 'Kit calls the first message attached to a form or landing page the confirmation email. It can ask the subscriber to confirm their address and can deliver a lead-magnet file after the click. That is not the same as a welcome sequence.' },
    {
      type: 'list',
      items: [
        [{ text: 'Confirmation email:', strong: true }, ' handles consent confirmation and, optionally, incentive delivery.'],
        [{ text: 'Welcome email:', strong: true }, ' introduces the newsletter or business after signup.'],
        [{ text: 'Welcome sequence:', strong: true }, ' two or more automated emails sent over time.'],
      ],
    },
    { type: 'paragraph', text: ['Kit says disabling the confirmation email also disables double opt-in. With double opt-in enabled, a subscriber must click the confirmation link before becoming confirmed. ', { text: 'Kit recommends', href: 'https://help.kit.com/en/articles/2971364-the-all-important-double-opt-in' }, ' keeping this setting on by default.'] },
    { type: 'paragraph', text: 'For a simple lead magnet, one carefully written confirmation email may be enough at the beginning. It can explain what the reader requested and take them to the file, but it should not be described as a full welcome sequence.' },
    { type: 'heading', level: 2, id: 'lead-magnet-workflow', text: 'The simple lead-magnet workflow' },
    {
      type: 'workflow',
      caption: 'Documented signup flow and current advanced-automation boundary',
      paths: [
        { title: 'Kit Free / Newsletter', steps: ['Form or landing page', 'Confirmation and double opt-in', 'Lead-magnet delivery', 'One sequence', 'Basic action-only automation'] },
        { title: 'Creator workflow', steps: ['Multiple sequences', 'Event or condition steps', 'Rules and advanced paths', 'Subscriber control'] },
      ],
    },
    { type: 'heading', level: 3, id: 'free-workflow', text: 'What Free can do' },
    { type: 'paragraph', text: 'On Free, you can build the form or landing page, configure the confirmation email, deliver a file, organize subscribers, send broadcasts and run one fixed sequence through one basic action-only automation.' },
    { type: 'paragraph', text: 'That can support a deliberately simple newsletter with one lead magnet, one audience, a clear confirmation message and one welcome path.' },
    { type: 'heading', level: 3, id: 'creator-boundary', text: 'Where Creator becomes necessary' },
    { type: 'paragraph', text: 'Upgrade pressure appears when the workflow needs more than one sequence or more than the basic action-only automation. Paid plans add unlimited sequences and advanced event, condition and rule functionality.' },
    {
      type: 'list',
      items: [
        'more than one automated sequence;',
        'different follow-up sequences for different forms;',
        'rules that react to subscriber activity;',
        'several automation paths; or',
        'an RSS-based email campaign.',
      ],
    },
    { type: 'paragraph', text: 'Do not pay for automation as an abstract benefit. Write the exact flow first. If you cannot name the second email, its delay and the reason it needs to be automatic, the paid plan may be premature.' },
    { type: 'heading', level: 2, id: 'subscriber-counting', text: 'What counts toward your subscriber limit' },
    { type: 'paragraph', text: 'Kit’s subscriber-status documentation says only confirmed subscribers count toward billing and can be emailed through Kit. This includes cold subscribers that remain confirmed.' },
    { type: 'paragraph', text: 'Unconfirmed subscribers have not completed the confirmation step. They do not count toward billing and cannot be emailed. Unsubscribed subscribers remain in the account with their historical data, but they do not count toward billing and cannot receive further Kit email.' },
    {
      type: 'list',
      ordered: true,
      items: [
        'A high raw signup count is not necessarily the same as the billable list size.',
        'A confirmed but inactive list can still push the account into a higher subscriber tier.',
      ],
    },
    { type: 'paragraph', text: 'List cleaning should be a considered editorial and data decision. Export a backup, define inactivity consistently and distinguish unsubscribing from deleting. Kit says deleting removes the subscriber and historical data, while unsubscribing retains history.' },
    { type: 'heading', level: 2, id: 'price', text: 'Price and upgrade triggers' },
    { type: 'paragraph', text: 'Kit’s public pricing page displayed these US-dollar prices for up to 1,000 subscribers when checked on 24 September 2026.' },
    {
      type: 'pricing',
      caption: 'Displayed pricing and billing cadence',
      columns: ['Plan', 'Displayed price', 'Billing note'],
      rows: [
        ['Free', '$0/month', 'Up to 10,000 subscribers under current plan terms'],
        ['Creator', '$33/month equivalent', '$390 billed yearly; page says this saves $78 per year'],
        ['Pro', '$66/month equivalent', '$790 billed yearly; page says this saves $158 per year'],
      ],
    },
    { type: 'note', title: 'Check the live checkout', text: 'A current Kit help article separately lists starting monthly prices of $39 for Creator and $79 for Pro at up to 1,000 subscribers. These figures represent a different billing cadence. Confirm subscriber tier, currency, tax, billing cadence and renewal term before paying.' },
    {
      type: 'list',
      items: [
        'a documented need for an automated welcome sequence;',
        'more than one repeatable subscriber journey;',
        'rules or RSS campaigns that remove recurring manual work;',
        'a paid integration the workflow genuinely requires; or',
        'Pro-only reporting or collaboration that affects a real operating decision.',
      ],
    },
    { type: 'paragraph', text: 'List growth alone is not a sufficient upgrade trigger while the current Free plan supports up to 10,000 subscribers.' },
    { type: 'heading', level: 2, id: 'integrations-export', text: 'Integrations, export and leaving later' },
    { type: 'paragraph', text: 'Kit lists API access on the Free plan. Its app documentation says some apps are available on Free while others display an upgrade requirement. Check the exact integration before choosing a plan.' },
    { type: 'paragraph', text: 'Kit documents CSV export for subscribers and filtered groups. A regular export provides a portable backup of the audience data the platform allows you to download.' },
    {
      type: 'list',
      items: [
        'export the full subscriber list and open the CSV;',
        'export a tagged or filtered group;',
        'unsubscribe a test address and confirm that sending stops;',
        'distinguish unsubscribe from permanent deletion;',
        'record which fields, tags and timestamps appear; and',
        'confirm how an imported contact is treated before migration.',
      ],
    },
    { type: 'paragraph', text: 'Documentation can establish that the controls exist. Only an account-level test can show whether the current interface and exported fields fit your process.' },
    { type: 'heading', level: 2, id: 'launch-tests', text: 'Practical limitations to test before launch' },
    { type: 'paragraph', text: 'This review does not claim firsthand results. These checks remain part of Domsky’s pre-publication product test and should also form the reader’s launch checklist.' },
    {
      type: 'table',
      caption: 'Signup-to-unsubscribe workflow checks',
      columns: ['Test', 'What to verify', 'Why it matters'],
      rows: [
        ['Form submission', 'Success state, mobile usability and stored fields', 'Prevents a broken first step'],
        ['Confirmation', 'Message arrives, sender is recognizable and link works', 'Confirms the consent path'],
        ['Lead-magnet delivery', 'Correct file or page appears after the click', 'Prevents a poor first impression'],
        ['Welcome flow', 'Correct message or paid sequence starts once', 'Catches duplicate or missing entry logic'],
        ['Tagging', 'Expected tag appears and no unrelated tag is added', 'Keeps later targeting reliable'],
        ['Unsubscribe', 'Test address stops receiving email', 'Checks a basic subscriber-control requirement'],
        ['Export', 'CSV opens and contains the fields you need', 'Reduces platform lock-in'],
        ['Mobile rendering', 'Form and email remain readable on a phone', 'Protects the common signup path'],
      ],
    },
    { type: 'paragraph', text: 'Email placement can vary by sender setup, domain reputation, recipient provider and message content. A successful test to one inbox does not prove universal deliverability. This article makes no inbox-placement promise.' },
    { type: 'heading', level: 2, id: 'plan-fit', text: 'Which plan fits which creator' },
    {
      type: 'table',
      caption: 'Situation-to-plan recommendation',
      columns: ['Situation', 'Start with', 'Reason'],
      rows: [
        ['New newsletter, one form, regular manual sends', 'Free', 'The included form, confirmation and broadcasts cover the workflow'],
        ['One lead magnet, no multi-email follow-up yet', 'Free', 'Use the confirmation email for delivery and add broadcasts deliberately'],
        ['One fixed welcome series after signup', 'Free', 'Current Newsletter Plan documentation includes one sequence and one basic automation'],
        ['Several lead magnets with different follow-up paths', 'Creator', 'Multiple sequences and automation actions are the relevant value'],
        ['Team members need access and advanced reporting', 'Pro', 'Pro adds unlimited users and deeper analytics/reporting'],
        ['Newsletter-first media business comparing platforms', 'Compare first', 'Another platform may better match the operating model'],
      ],
    },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Most beginners should choose between Free and Creator. Pro should solve a named reporting or collaboration problem, not serve as a status upgrade.'] },
    { type: 'heading', level: 2, id: 'poor-fit', text: 'When Kit is not the best fit' },
    {
      type: 'list',
      items: [
        'several sequences or advanced branching are required but the paid price is outside the budget;',
        'a required integration is unavailable or requires an unwanted upgrade;',
        'the primary product is a publication and another newsletter-site or advertising model fits better;',
        'the team needs a traditional marketing suite with broader CRM functions; or',
        'another tool’s free plan includes the exact automation being planned.',
      ],
    },
    { type: 'paragraph', text: ['Those are workflow mismatches, not evidence that Kit is generally bad. ', { text: 'Compare Kit, MailerLite and beehiiv', href: '/comparisons/kit-vs-mailerlite-vs-beehiiv' }, ' using the same subscriber count, billing cadence and required workflow.'] },
    { type: 'heading', level: 2, id: 'recommendation', text: 'Domsky recommendation' },
    {
      type: 'decisionCards',
      cards: [
        { label: 'One fixed welcome path', title: 'Choose Free', tool: 'Kit Free', text: 'Use it for a form, incentive delivery, one sequence, a basic automation and broadcasts.' },
        { label: 'Several subscriber journeys', title: 'Choose Creator', tool: 'Kit Creator', text: 'Use it when multiple sequences, advanced steps or branching are part of the current plan.' },
        { label: 'Team and reporting needs', title: 'Choose Pro carefully', tool: 'Kit Pro', text: 'Use it only for a named collaboration or reporting requirement.' },
      ],
    },
    { type: 'paragraph', text: 'The practical rule is simple: pay for the first required workflow that Free cannot run. Before committing, complete one full signup-to-unsubscribe test and export the resulting test record.' },
    { type: 'paragraph', text: ['Before adding email software at all, use the ', { text: 'lean solo-business stack guide', href: '/uses' }, ' to decide whether subscriber capture and planned email are current jobs or categories that can wait.'] },
    { type: 'cta', title: 'Map your workflow before choosing a plan', text: 'If one sequence and a basic automation are enough, start with Free. If you need several or advanced paths, verify the current Creator checkout price.', label: 'Review the workflow boundary', href: '#lead-magnet-workflow' },
    { type: 'heading', level: 2, id: 'questions', text: 'Common questions' },
    { type: 'heading', level: 3, id: 'convertkit-name', text: 'Is Kit still ConvertKit?' },
    { type: 'paragraph', text: 'Kit is the current product name; the company describes it as formerly ConvertKit. This page keeps the older /reviews/convertkit route so existing links do not need to change.' },
    { type: 'heading', level: 3, id: 'free-subscribers', text: 'Is Kit really free for up to 10,000 subscribers?' },
    { type: 'paragraph', text: 'Kit’s current Free-plan and pricing pages say yes, subject to current terms. The plan includes forms, landing pages, broadcasts, tagging and segmentation, but not every automation or app feature.' },
    { type: 'heading', level: 3, id: 'free-sequence', text: 'Can Kit Free send a welcome sequence?' },
    { type: 'paragraph', text: 'Yes, within the current Newsletter Plan boundary: one Email Sequence and one basic action-only Visual Automation. Unlimited sequences and advanced automation require a paid plan.' },
    { type: 'heading', level: 3, id: 'confirmation-welcome', text: 'Does the confirmation email count as a welcome email?' },
    { type: 'paragraph', text: 'It can welcome the subscriber and deliver a file, but it is primarily the confirmation and incentive step. It is not the same as a timed multi-email welcome sequence.' },
    { type: 'heading', level: 3, id: 'billing-subscribers', text: 'Which subscribers count toward billing?' },
    { type: 'paragraph', text: 'Kit says confirmed subscribers count toward billing and can be emailed. Unconfirmed and unsubscribed contacts do not count. Confirmed cold subscribers remain in the total.' },
    { type: 'heading', level: 3, id: 'export-list', text: 'Can I export my list?' },
    { type: 'paragraph', text: 'Kit documents CSV exports for the subscriber list and subsets. Test the current export before launch to confirm that it contains the fields and organization you need.' },
    { type: 'paragraph', text: 'Pricing, plan boundaries and workflow descriptions come from Kit’s official pages listed below. Domsky has not completed its controlled workflow test, so this review does not rate setup ease, delivery speed, inbox placement or support quality.' },
    { type: 'sources', id: 'sources', title: 'Sources and evidence limits' },
  ],
} satisfies ArticleDocument;
