import type { ArticleDocument } from '../types';
import { PUBLIC_AUTHOR } from '../../data/site';

export const emailPlatformComparison = {
  id: 'dce-05-kit-mailerlite-beehiiv',
  title: 'Kit vs MailerLite vs beehiiv: Choose for a Lead Magnet or a Newsletter Business',
  slug: '/comparisons/kit-vs-mailerlite-vs-beehiiv',
  description: 'Compare Kit, MailerLite and beehiiv for lead magnets, welcome sequences and newsletter businesses, with current limits and equal-size pricing.',
  excerpt: 'Choose an email platform by the subscriber journey it must complete, then compare free limits, automation boundaries and equal-size monthly prices.',
  deck: 'Compare the lowest sufficient plan for a lead magnet, welcome sequence or newsletter business—without declaring a universal winner.',
  seoTitle: 'Kit vs MailerLite vs beehiiv for Creators | Domsky',
  socialTitle: 'Kit vs MailerLite vs beehiiv: Choose by Workflow',
  socialDescription: 'Compare free limits, welcome automation and equal-size monthly pricing before choosing an email platform.',
  category: 'Comparisons',
  author: PUBLIC_AUTHOR,
  publishedAt: '2026-09-25',
  updatedAt: '2026-09-25',
  verifiedAt: '2026-09-25',
  status: 'published',
  contentType: 'comparison',
  tags: ['Kit', 'MailerLite', 'beehiiv', 'Email marketing', 'Lead magnets', 'Newsletters'],
  relatedSlugs: ['/reviews/convertkit', '/blog/ai-daily-workflow-solo-business'],
  readingMinutes: 16,
  featuredImageRequired: true,
  featuredImage: {
    src: '/images/kit-mailerlite-beehiiv-workflows.svg',
    alt: 'Kit, MailerLite and beehiiv compared across lead magnet, welcome sequence and newsletter business workflows.',
    caption: 'Choose by the workflow email must complete. Editorial illustration by Domsky Solutions.',
    width: 1600,
    height: 900,
  },
  ogImage: {
    src: '/images/kit-mailerlite-beehiiv-workflows.svg',
    alt: 'Kit, MailerLite and beehiiv compared across three email workflows.',
    width: 1600,
    height: 900,
  },
  commercial: true,
  recommendedUpdateDays: 7,
  affiliateDisclosureRequired: false,
  disclosure: 'No affiliate tracking links are included. Product links and citations are direct provider URLs, and recommendations remain editorially independent.',
  verificationPending: [],
  sources: [
    { id: 'kit-01', title: 'Kit: Pricing and plan comparison', url: 'https://kit.com/pricing' },
    { id: 'kit-02', title: 'Kit Help Center: The Kit Free plan', url: 'https://help.kit.com/en/articles/16627071-the-kit-free-plan' },
    { id: 'kit-02b', title: 'Kit Help Center: Visual Automations on the Newsletter Plan', url: 'https://help.kit.com/en/articles/9053626-visual-automations-on-the-newsletter-plan' },
    { id: 'kit-03', title: 'Kit Help Center: Billing at Kit', url: 'https://help.kit.com/en/articles/2502679-billing-at-kit' },
    { id: 'kit-04', title: 'Kit Help Center: The Confirmation Email', url: 'https://help.kit.com/en/articles/2502655-the-confirmation-email' },
    { id: 'kit-05', title: 'Kit Help Center: Grow your list with content upgrades', url: 'https://help.kit.com/en/articles/2502644-grow-your-list-with-content-upgrades' },
    { id: 'kit-06', title: 'Kit Help Center: Creating and sending an Email Sequence', url: 'https://help.kit.com/en/articles/2502629-creating-and-sending-an-email-sequence-in-kit' },
    { id: 'kit-07', title: 'Kit Help Center: How to export subscribers', url: 'https://help.kit.com/en/articles/2502489-how-to-export-subscribers-in-kit' },
    { id: 'kit-08', title: 'Kit: Affiliate Program', url: 'https://kit.com/affiliate' },
    { id: 'ml-01', title: 'MailerLite: Pricing and plan comparison', url: 'https://www.mailerlite.com/pricing' },
    { id: 'ml-02', title: 'MailerLite Help: Free plan update', url: 'https://www.mailerlite.com/help/free-plan-update-faq' },
    { id: 'ml-03', title: 'MailerLite Help: Plan and billing', url: 'https://www.mailerlite.com/help/plan-and-billing' },
    { id: 'ml-04', title: 'MailerLite Help: How to send a freebie to new subscribers', url: 'https://www.mailerlite.com/help/how-to-send-a-freebie-lead-magnet-to-new-subscribers' },
    { id: 'ml-05', title: 'MailerLite: Signup forms', url: 'https://www.mailerlite.com/features/signup-forms' },
    { id: 'ml-06', title: 'MailerLite: Affiliate Program', url: 'https://www.mailerlite.com/affiliate' },
    { id: 'ml-07', title: 'MailerLite: Affiliate Program Terms', url: 'https://www.mailerlite.com/legal/affiliate-program-terms' },
    { id: 'bh-01', title: 'beehiiv: Pricing and feature comparison', url: 'https://www.beehiiv.com/pricing' },
    { id: 'bh-02', title: 'beehiiv Help: Plan types and subscriber-plan tiers', url: 'https://www.beehiiv.com/support/article/23874462928663-plan-types-and-subscriber-plan-tier-pricing' },
    { id: 'bh-03', title: 'beehiiv Help: Welcome email vs welcome automation', url: 'https://www.beehiiv.com/support/article/38813477234071-welcome-email-vs-welcome-automation-which-should-you-use' },
    { id: 'bh-04', title: 'beehiiv Help: Double opt-in and Smart Nudge', url: 'https://www.beehiiv.com/support/article/13081072798743-how-to-enable-double-opt-in-and-smart-nudge' },
    { id: 'bh-05', title: 'beehiiv Help: Automation workflows', url: 'https://www.beehiiv.com/support/article/18743686099991-types-of-workflows-how-to-create-automations-for-your-subscribers' },
    { id: 'bh-06', title: 'beehiiv Help: Exporting post content or subscriber data', url: 'https://www.beehiiv.com/support/article/12258595483543-exporting-post-content-or-subscriber-data-from-beehiiv' },
    { id: 'bh-07', title: 'beehiiv: Partner Program', url: 'https://www.beehiiv.com/partners/affiliate' },
  ],
  blocks: [
    {
      type: 'note',
      title: 'Documentation-based comparison',
      text: [
        'This comparison uses Kit, MailerLite and beehiiv pricing pages and help centers checked on 25 September 2026. Domsky has not completed a matched signup-to-unsubscribe test for all three products. Product capabilities are attributed to the providers; the recommendations are Domsky editorial analysis. ',
        { text: 'See how Domsky verifies software claims', href: '/methodology' },
        '.',
      ],
    },
    { type: 'paragraph', text: 'Kit, MailerLite and beehiiv can all collect subscribers and send email. They are not interchangeable.' },
    { type: 'paragraph', text: 'The practical choice depends on what email does for your business:' },
    {
      type: 'list',
      items: [
        'If email supports a service, course or digital product, start with the lead-magnet and follow-up workflow.',
        'If you need campaigns plus a short automated sequence, compare the first plan that includes enough automation.',
        'If the newsletter, its website and its monetization system are the product, compare newsletter-publishing features rather than only forms and email sends.',
      ],
    },
    { type: 'paragraph', text: 'There is no universal winner. The useful goal is the lowest sufficient plan that completes your workflow without forcing an early rebuild.' },
    { type: 'paragraph', text: ['No affiliate tracking links are included. Read the ', { text: 'affiliate disclosure', href: '/disclaimer' }, ' before any future commercial link is added.'] },
    { type: 'heading', level: 2, id: 'short-answer', text: 'The short answer' },
    {
      type: 'quickVerdict',
      label: 'At a glance',
      summary: 'Choose by business model and subscriber journey first, then compare the lowest plan that completes that journey at the same active-subscriber count and billing cadence.',
      bestFor: 'Kit Free for a lead magnet and one fixed welcome sequence with large list headroom; MailerLite Free or Comfort for several small automations; beehiiv Launch or Scale when the newsletter is the product.',
      notFor: 'Anyone looking for a permanent winner independent of workflow, list size or required automation.',
      verdict: 'Use the least complex plan that completes the next 90 days of work.',
    },
    { type: 'paragraph', text: [{ text: 'Choose Kit', strong: true }, ' when you want a creator-focused list for a service, product or audience business, value generous free list headroom, and need no more than one fixed welcome sequence. Kit’s current Newsletter Plan help article documents one Email Sequence and one basic action-only Visual Automation; Creator adds unlimited sequences and advanced automation.'] },
    { type: 'paragraph', text: [{ text: 'Choose MailerLite', strong: true }, ' when you need a conventional email-marketing toolkit—forms, landing pages, campaigns and multi-email automations—at the lowest verified paid price in this comparison. Its Free plan includes up to three automations, but the current ceiling is 250 active subscribers and 2,500 sends per month.'] },
    { type: 'paragraph', text: [{ text: 'Choose beehiiv', strong: true }, ' when the newsletter and its web presence are central to the business. Launch includes up to 2,500 active subscribers, unlimited sends, a hosted website and a single welcome email. Scale adds multi-step automations, paid subscriptions, the Ad Network, digital products and other newsletter-business tools.'] },
    { type: 'paragraph', text: 'That recommendation comes from current product documentation, not a deliverability test. Domsky has not measured inbox placement or conversion rates across the three tools.' },
    { type: 'heading', level: 2, id: 'job-email-performs', text: 'Start with the job email performs' },
    { type: 'heading', level: 3, id: 'lead-magnet', text: '1. A lead magnet for a service or product' },
    { type: 'paragraph', text: 'The basic journey is:' },
    {
      type: 'process',
      title: 'One-message lead-magnet journey',
      steps: [
        { title: 'Collect', description: 'A visitor submits a form or landing page.' },
        { title: 'Confirm', description: 'The platform sends a confirmation email when double opt-in is enabled.' },
        { title: 'Deliver', description: 'The subscriber receives the promised resource or a welcome message.' },
        { title: 'Continue', description: 'The creator sends later campaigns with a clear unsubscribe option.' },
      ],
    },
    { type: 'paragraph', text: 'For this narrow job, you may not need a multi-step automation.' },
    { type: 'paragraph', text: 'Kit documents opt-in incentive delivery on all plans. MailerLite documents delivery through its double-opt-in confirmation thank-you page, and it can also use an automation. beehiiv provides a single welcome email on every plan; that message can direct confirmed subscribers to the resource, while its dedicated multi-step lead-magnet automation belongs to paid automation functionality.' },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Kit Free gives the most list headroom here and can support one fixed welcome sequence under the current specific help documentation. MailerLite Free supports several small automations but has a much lower subscriber ceiling. beehiiv is reasonable when the lead magnet feeds a newsletter publication rather than a broader service funnel.'] },
    { type: 'heading', level: 3, id: 'campaigns-welcome-sequence', text: '2. Campaigns and a welcome sequence' },
    { type: 'paragraph', text: 'A sequence is different from a confirmation email or a single welcome email. It may send several messages over several days and branch or tag subscribers based on their actions.' },
    {
      type: 'list',
      items: [
        'Kit Free / Newsletter includes one Email Sequence and one basic action-only Visual Automation. Creator adds unlimited sequences and advanced automations.',
        'MailerLite Free includes up to three active automations, with up to five steps per automation under the current comparison table. Comfort raises that to 50 active automations and up to 100 steps.',
        'beehiiv Launch includes one standalone welcome email but not Automations. Scale adds multi-step automations.',
      ],
    },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'MailerLite has the lowest-cost route to a real welcome series. Kit becomes more compelling when its creator-specific tagging, commerce and broader audience workflow are more important than the initial price. beehiiv’s paid automation makes most sense when the same account is also running the publication website and newsletter monetization.'] },
    { type: 'heading', level: 3, id: 'newsletter-product', text: '3. A newsletter that is the product' },
    { type: 'paragraph', text: 'If the newsletter itself is the product, the platform may need to provide a hosted publication, recommendation or referral tools, paid subscriptions, advertising access and newsletter-specific analytics.' },
    { type: 'paragraph', text: 'beehiiv is designed around that model. Launch includes newsletters, a website, recommendation-network access and unlimited sends. Scale adds the Ad Network, paid subscriptions with a stated 0% platform take rate, digital products, a referral program, surveys and automations. Payment-processing and eligibility conditions still need to be checked separately.' },
    { type: 'paragraph', text: 'Kit also supports a newsletter feed or website, paid newsletters, digital products and recurring subscriptions on its plans. Its current pricing table lists a 3.5% + $0.30 charge for digital products and subscriptions, including payment processing, and applies a separate fee to Paid Recommendations earnings on paid plans.' },
    { type: 'paragraph', text: 'MailerLite supports websites, paid newsletters, digital products and recurring subscriptions alongside general email marketing. It is broader than a newsletter-only tool, which can be useful for a small business with several types of customer communication.' },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'beehiiv has the clearest default fit for a publication-led business. Kit is stronger when the same list supports multiple creator products or services. MailerLite is the practical generalist when campaigns and automations matter more than a native newsletter-growth ecosystem.'] },
    { type: 'heading', level: 2, id: 'free-plans', text: 'What each free plan can complete' },
    { type: 'paragraph', text: 'The table below reports documented support. It does not claim that Domsky completed each workflow.' },
    {
      type: 'table',
      caption: 'Documented free-plan workflow support checked 25 September 2026',
      columns: ['Requirement', 'Kit Free', 'MailerLite Free', 'beehiiv Launch'],
      rows: [
        ['Free subscriber allowance', 'Up to 10,000 subscribers', 'Up to 250 active subscribers', 'Up to 2,500 active subscribers'],
        ['Send allowance', 'Unlimited broadcasts under current pricing FAQ', '2,500 sends per month', 'Unlimited sends'],
        ['Forms / landing pages', 'Unlimited forms and landing pages', '3 active forms; 1 landing page; 1 website', 'Subscribe forms and hosted website included'],
        ['Confirmation / double opt-in', 'Supported; confirmation can deliver an incentive', 'Supported; confirmation thank-you page can link to the resource', 'Supported; subscriber remains Pending until confirmed'],
        ['One delivery or welcome message', 'Opt-in incentive email', 'Confirmation page/email or an automation', 'One standalone welcome email'],
        ['Multi-email automation', 'One sequence + one basic action-only automation', 'Yes, within Free limits', 'No'],
        ['Segmentation', 'Tags and segments', 'Groups/tags and dynamic segments', 'Segments and custom fields'],
        ['Platform branding removable on Free', 'No under current table', 'No; paid plan removes it', 'No; current table places removal on Max'],
        ['Best initial fit', 'Simple lead magnet with large free headroom', 'Small list needing a short automation', 'Newsletter publication with one welcome email'],
      ],
    },
    { type: 'paragraph', text: 'The Free plan is not always the lowest-cost long-term choice. A platform that stops before the required automation can create more work than starting on the correct paid tier.' },
    { type: 'heading', level: 2, id: 'subscriber-journey', text: 'The same subscriber journey compared' },
    {
      type: 'table',
      caption: 'One subscriber journey across all three platforms',
      columns: ['Journey step', 'Kit', 'MailerLite', 'beehiiv'],
      rows: [
        ['Collect the signup', 'Form or landing page', 'Form, pop-up or landing page', 'Subscribe form or hosted site'],
        ['Confirm consent', 'Confirmation email / double opt-in setting', 'Double-opt-in email and confirmation page', 'Double-opt-in email; Pending until confirmed'],
        ['Deliver one resource', 'Opt-in incentive delivery', 'Confirmation thank-you link or automation email', 'Standalone welcome email can link to it'],
        ['Send several welcome emails', 'One Free sequence; Creator for unlimited/advanced paths', 'Free within limits; Comfort for more capacity', 'Scale automation'],
        ['Organize subscribers', 'Tags and segments', 'Groups/tags and dynamic segments', 'Segments, tags/custom fields'],
        ['Send regular newsletter', 'Broadcast', 'Campaign', 'Post/newsletter send'],
        ['Export subscribers', 'CSV export documented', 'CSV export documented', 'Quick or Full subscriber export documented'],
        ['Unsubscribe', 'Supported; record retained unless deleted', 'Supported; active/unsubscribed status affects counting', 'Supported; inactive/suppressed states handled separately'],
      ],
    },
    { type: 'paragraph', text: 'This matrix shows why a single “free plan” label is not enough. Kit has the largest free audience allowance and one limited sequence/automation path. MailerLite includes several small automations for a much smaller audience. beehiiv includes the publishing system and one welcome email, while reserving multi-step automation and most monetization features for Scale.' },
    { type: 'heading', level: 2, id: 'automation', text: 'What changes when you need automation' },
    { type: 'paragraph', text: 'Automation becomes the upgrade trigger when one message is no longer enough.' },
    { type: 'list', items: ['a three- or five-email welcome series;', 'different follow-up based on the form used;', 'delays between emails;', 'branches based on tags, clicks or custom fields;', 'removing a person from a pitch after purchase; or', 're-engaging an inactive segment.'] },
    { type: 'paragraph', text: 'MailerLite Free can cover a small, simple version of this workflow. Its current limits are three active automations and five steps per automation, with a 250-active-subscriber and 2,500-send monthly ceiling. Comfort expands capacity and removes MailerLite branding.' },
    { type: 'paragraph', text: 'Kit Free can handle one fixed sequence and one basic action-only automation. Creator becomes relevant when the workflow needs more sequences, event or condition steps, rules, paid apps and integrations, RSS campaigns, Kit MCP access or branding removal.' },
    { type: 'paragraph', text: 'beehiiv requires Scale for automations. The same upgrade also adds newsletter-business features such as paid subscriptions, the Ad Network, digital products and advanced analytics. Paying for Scale only to deliver a three-email lead magnet may be unnecessary if the newsletter-business features are not part of the plan.' },
    { type: 'heading', level: 2, id: 'monthly-cost', text: 'Monthly cost at 1,000 and 5,000 subscribers' },
    { type: 'paragraph', text: 'These figures use USD month-to-month billing, the current public calculators and the lowest plan in each product that supports one fixed multi-email welcome sequence at the stated list size. Taxes, regional currency, trials and add-ons are excluded.' },
    {
      type: 'pricing',
      caption: 'Month-to-month prices checked 25 September 2026',
      columns: ['Active subscribers', 'MailerLite sufficient plan', 'Kit sufficient plan', 'beehiiv sufficient plan'],
      rows: [
        ['1,000', 'Comfort — $19/month', 'Free / Newsletter — $0', 'Scale — $49/month'],
        ['5,000', 'Comfort — $49/month', 'Free / Newsletter — $0', 'Scale — $89/month'],
      ],
    },
    { type: 'note', title: 'Compare the workflow and billing cadence', text: 'The Kit figures assume one sequence and one basic automation are sufficient. If unlimited sequences or advanced automation are required, Creator was $39 month-to-month at 1,000 subscribers and $89 at 5,000. Annual equivalents shown on the same date were $33 and $75. beehiiv showed Scale at $43 and $78 annually; MailerLite advertises a 10% annual discount.' },
    { type: 'paragraph', text: 'Price alone does not settle the decision:' },
    { type: 'list', items: ['MailerLite Comfort has send limits equal to 10 times the ceiling of the subscriber tier. At 5,000, that is 50,000 sends per month.', 'Kit’s current FAQ states that its plans do not impose email-send limits.', 'beehiiv lists unlimited sends on Launch, Scale and Max.'] },
    { type: 'paragraph', text: 'Estimate your actual monthly sends. A weekly newsletter to 5,000 subscribers uses roughly 20,000 sends before automations or resends. MailerLite Comfort’s documented allowance covers that example, but a higher-frequency operation may need Power.' },
    { type: 'heading', level: 2, id: 'subscriber-counting', text: 'Subscriber counting is not identical' },
    { type: 'paragraph', text: '“5,000 subscribers” must mean the same thing before comparing price.' },
    { type: 'paragraph', text: 'Kit states that billing is based on confirmed or active subscribers rather than email sends. Unconfirmed and unsubscribed records do not count in the same way as confirmed subscribers, although subscriber-state handling should be checked before cleaning a list.' },
    { type: 'paragraph', text: 'MailerLite counts unique subscribers with Active status. Its help center also states that the count is cumulative during a billing cycle: an address that was Active earlier in the cycle can still count until the billing anniversary even if later deleted. Unsubscribed and bounced contacts do not count as active.' },
    { type: 'paragraph', text: 'beehiiv prices paid tiers by active subscribers. The current help documentation defines an active subscriber as someone being sent to who has not unsubscribed or been marked inactive. Launch allows up to 2,500 active subscribers; paid plan cost rises by subscriber tier.' },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Do not compare a cleaned active list on one platform with every imported contact on another. Record the active, pending, unsubscribed, bounced and suppressed totals first.'] },
    { type: 'heading', level: 2, id: 'switching', text: 'Switching involves more than a CSV' },
    { type: 'paragraph', text: 'All three platforms document subscriber export. That does not mean a migration preserves the whole system.' },
    { type: 'list', items: ['email address and subscriber status;', 'consent source and date, where available;', 'tags, groups, segments and custom fields;', 'forms and landing pages;', 'confirmation and welcome emails;', 'automation logic and delays;', 'newsletter archives or posts;', 'paid-subscription records;', 'sending domain and authentication;', 'integrations, webhooks and API connections; and', 'unsubscribe or suppression records.'] },
    { type: 'paragraph', text: 'A CSV usually moves contacts and selected fields. It does not reproduce automations, form embeds, website design, historical analytics or every consent record. Rebuild and test those separately.' },
    { type: 'paragraph', text: 'If an existing platform already completes the workflow at an acceptable cost, migration should solve a specific recurring problem—not provide a temporary sense of progress.' },
    { type: 'heading', level: 2, id: 'situations', text: 'Which platform fits each situation?' },
    {
      type: 'table',
      caption: 'Conditional recommendation by situation',
      columns: ['Situation', 'Choose first', 'Why', 'Main limitation to accept'],
      rows: [
        ['One lead magnet, broadcasts and one fixed welcome sequence', 'Kit Free / Newsletter', 'Up to 10,000 subscribers, incentive delivery, one sequence and one basic automation', 'Only one sequence; no advanced branching'],
        ['Lead magnet plus a short welcome series under 250 subscribers', 'MailerLite Free', 'Limited automations are included', 'Low subscriber and monthly-send ceilings'],
        ['General small-business email with several automations', 'MailerLite Comfort', 'Lowest verified paid automation price here; broad forms/site toolkit', 'Send allowance is tier-based, not unlimited'],
        ['Service or product creator needing deeper tagging and creator commerce', 'Kit Creator', 'Sequences, visual automation, integrations and creator-oriented commerce', 'Higher price than MailerLite at equal list sizes'],
        ['Free newsletter publication with a website and one welcome email', 'beehiiv Launch', 'Up to 2,500 active subscribers, unlimited sends and publication tools', 'No multi-step automation or native paid-newsletter tools'],
        ['Newsletter business using ads, paid subscriptions and referrals', 'beehiiv Scale', 'Newsletter growth and monetization tools live in one system', 'Costs more than general email marketing; branding remains under current table'],
        ['Existing account already works', 'Keep it', 'Avoids migration and retraining', 'Reassess only when a documented requirement is unmet'],
      ],
    },
    { type: 'paragraph', text: 'These are editorial recommendations based on documented fit. They are not rankings of deliverability or usability.' },
    { type: 'heading', level: 2, id: 'recommendation', text: 'Domsky recommendation' },
    { type: 'paragraph', text: 'For most beginners, start by writing the subscriber journey in one line:' },
    { type: 'quote', text: 'Form → confirmation → resource or welcome email → follow-up sequence → regular email → unsubscribe/export.' },
    { type: 'paragraph', text: 'Then mark which steps are required now.' },
    {
      type: 'decisionCards',
      cards: [
        { label: 'One fixed welcome sequence', title: 'Start with Kit Free', tool: 'Kit Free / Newsletter', text: 'The cleanest starting point here when one resource and one basic welcome sequence complete the workflow.' },
        { label: 'Several automated follow-ups', title: 'Start with MailerLite', tool: 'MailerLite Free or Comfort', text: 'Use Free to test a small sequence, then move to Comfort when subscriber, send or feature limits become restrictive.' },
        { label: 'Newsletter and site are the product', title: 'Start with beehiiv', tool: 'beehiiv Launch or Scale', text: 'Use Launch first, then move to Scale when automation or monetization features are genuinely needed.' },
        { label: 'Working account already fits', title: 'Keep it', text: 'Stay until a measured limitation justifies the cost and work of switching.' },
      ],
    },
    { type: 'paragraph', text: 'Do not pay for three overlapping email platforms. Do not choose a paid tier because of a long feature list. Choose the least complex plan that completes the next 90 days of work.' },
    { type: 'paragraph', text: ['For a closer look at Kit’s current plan boundary, read the ', { text: 'Kit review and upgrade guide', href: '/reviews/convertkit' }, '. Domsky’s ', { text: 'methodology', href: '/methodology' }, ' explains how documentation-based and hands-on evidence are separated.'] },
    { type: 'cta', title: 'Choose by the subscriber journey', text: 'Write the required steps, find the lowest plan that completes them, and recheck the current plan before paying.', label: 'Review the workflow comparison', href: '#subscriber-journey' },
    { type: 'heading', level: 2, id: 'questions', text: 'Common questions' },
    { type: 'heading', level: 3, id: 'free-lead-magnet', text: 'Which free plan can deliver a lead magnet?' },
    { type: 'paragraph', text: 'All three can support a one-message lead-magnet journey in different ways. Kit documents opt-in incentive delivery. MailerLite can link the resource from the double-opt-in confirmation thank-you page or deliver it through an automation. beehiiv can send a standalone welcome email on Launch after confirmation. Test the exact journey before promoting it.' },
    { type: 'heading', level: 3, id: 'free-welcome-sequence', text: 'Which free plan includes a multi-email welcome sequence?' },
    { type: 'paragraph', text: 'MailerLite Free currently includes up to three active automations with limited steps. Kit Free / Newsletter includes one Email Sequence and one basic action-only Visual Automation. beehiiv Launch includes one welcome email but not a multi-step Automation. Kit Creator is needed for unlimited or advanced automation, while beehiiv Scale is needed for a multi-step series.' },
    { type: 'heading', level: 3, id: 'beehiiv-newsletters', text: 'Is beehiiv only for newsletters?' },
    { type: 'paragraph', text: 'It includes forms, a site, digital products and automations on eligible plans, so it can support broader creator workflows. Its strongest differentiation is still the publication, growth and monetization system around a newsletter.' },
    { type: 'heading', level: 3, id: 'kit-free-cost', text: 'Is Kit Free always cheaper than MailerLite?' },
    { type: 'paragraph', text: 'Kit Free has a much larger subscriber allowance and now documents one limited sequence and automation path. A creator who needs several sequences or advanced branching may still need Creator at $39 month-to-month at 1,000 subscribers, while MailerLite Comfort was $19 at the same list size on the verification date. Compare the workflow limits, not the free-plan headline.' },
    { type: 'heading', level: 3, id: 'export-before-switching', text: 'What should I export before switching?' },
    { type: 'paragraph', text: 'Export subscribers and every available field, then separately record statuses, consent evidence, tags, segments, automations, forms, domains, integrations and suppression data. Do not cancel the old account until the rebuilt signup, confirmation, sending, unsubscribe and export journey has been tested.' },
    { type: 'heading', level: 2, id: 'evidence-limits', text: 'Sources and evidence limits' },
    { type: 'paragraph', text: 'Plan and capability statements in this article come from official provider documentation checked on 25 September 2026. The price scenarios were read from each provider’s live public calculator at 1,000 and 5,000 subscribers with month-to-month billing selected.' },
    { type: 'paragraph', text: 'Domsky has not yet run the same form, confirmation, lead-magnet, automation, unsubscribe and export test across all three products. The article therefore makes no claim about setup time, interface quality, support quality, inbox placement or conversion performance. Prices and plan entitlements should be checked again within seven days of publication.' },
    { type: 'paragraph', text: ['See how this comparison research becomes an article, subscriber email and social draft in the ', { text: 'lean content workflow', href: '/blog/ai-daily-workflow-solo-business' }, '.'] },
    { type: 'sources', id: 'sources', title: 'Official sources' },
  ],
} satisfies ArticleDocument;

