import type { ArticleDocument } from '../types';

export const kitReview = {
  id: 'dce-04-kit-review',
  title: 'Kit Review for a Solo Creator: Free-Plan Limits, Welcome Emails and Upgrade Triggers',
  slug: '/reviews/convertkit',
  description: 'A practical Kit review for solo creators: what the Free plan includes, how lead magnets and welcome emails work, and when Creator is worth paying for.',
  excerpt: 'Kit Free can collect subscribers and send broadcasts, but a multi-email welcome workflow currently requires a paid plan. See the practical upgrade boundary.',
  deck: 'Define the email workflow you need, understand where automation becomes paid, and test subscriber controls before committing.',
  seoTitle: 'Kit Review for Solo Creators: Free Plan & Limits | Domsky',
  socialTitle: 'Kit Free or Creator? A Practical Solo-Creator Review',
  socialDescription: 'See what Kit Free can handle, where welcome automation becomes paid, and what to test before moving your list.',
  category: 'Email Marketing',
  author: { name: 'Domsky Solutions editorial', type: 'Organization', url: '/about' },
  publishedAt: '2026-09-25',
  updatedAt: '2026-09-25',
  verifiedAt: '2026-09-24',
  status: 'published',
  contentType: 'review',
  tags: ['Kit', 'ConvertKit', 'Email marketing', 'Lead magnets', 'Solo creators'],
  relatedSlugs: [],
  readingMinutes: 13,
  featuredImageRequired: true,
  featuredImage: {
    src: '/images/kit-free-vs-creator-workflow.svg',
    alt: 'Kit Free and Creator email workflows compared from signup to welcome sequence.',
    caption: 'Editorial workflow illustration. Product limits are based on Kit documentation checked 24 September 2026.',
    width: 1600,
    height: 900,
  },
  ogImage: {
    src: '/images/kit-free-vs-creator-workflow.svg',
    alt: 'Kit Free and Creator email workflows compared from signup to welcome sequence.',
    width: 1600,
    height: 900,
  },
  commercial: true,
  recommendedUpdateDays: 30,
  affiliateDisclosureRequired: false,
  disclosure: 'No monetized Kit link is included. Product links are direct, non-affiliate sources, and plan recommendations remain editorially independent.',
  verificationPending: [],
  sources: [
    { id: 'kit-01', title: 'Kit: Pricing and plans', url: 'https://kit.com/pricing' },
    { id: 'kit-02', title: 'Kit Help Center: The Kit Free plan', url: 'https://help.kit.com/en/articles/16627071-the-kit-free-plan' },
    { id: 'kit-03', title: 'Kit Help Center: Creator vs Pro — choose the right plan', url: 'https://help.kit.com/en/articles/4494683-creator-vs-pro-choose-the-right-plan' },
    { id: 'kit-04', title: 'Kit: Features', url: 'https://kit.com/features' },
    { id: 'kit-05', title: 'Kit Help Center: The Confirmation Email', url: 'https://help.kit.com/en/articles/2502655-the-confirmation-email' },
    { id: 'kit-06', title: 'Kit Help Center: The all-important double opt-in', url: 'https://help.kit.com/en/articles/2971364-the-all-important-double-opt-in' },
    { id: 'kit-07', title: 'Kit Help Center: Grow your list with content upgrades', url: 'https://help.kit.com/en/articles/2502644-grow-your-list-with-content-upgrades' },
    { id: 'kit-08', title: 'Kit Help Center: Creating and sending an Email Sequence', url: 'https://help.kit.com/en/articles/2502629-creating-and-sending-an-email-sequence-in-kit' },
    { id: 'kit-09', title: 'Kit Help Center: How to use Kit Visual Automations', url: 'https://help.kit.com/en/articles/2502666-how-to-use-kit-visual-automations' },
    { id: 'kit-10', title: 'Kit Help Center: Visual Automations actions', url: 'https://help.kit.com/en/articles/2502537-visual-automations-actions' },
    { id: 'kit-11', title: 'Kit Help Center: Subscriber profile page and status', url: 'https://help.kit.com/en/articles/2502651-the-subscriber-profile-page-and-status' },
    { id: 'kit-12', title: 'Kit Help Center: How to remove subscribers', url: 'https://help.kit.com/en/articles/2502654-how-to-remove-subscribers-from-your-email-list' },
    { id: 'kit-13', title: 'Kit Help Center: How to export subscribers', url: 'https://help.kit.com/en/articles/2502489-how-to-export-subscribers-in-kit' },
    { id: 'kit-14', title: 'Kit Help Center: Apps and integrations overview', url: 'https://help.kit.com/en/articles/9427509-apps-and-integrations-overview' },
    { id: 'kit-15', title: 'Kit Help Center: Kit API overview', url: 'https://help.kit.com/en/articles/9902901-kit-api-overview' },
    { id: 'kit-16', title: 'Kit: Affiliate Program', url: 'https://kit.com/affiliate' },
  ],
  blocks: [
    {
      type: 'note',
      title: 'Documentation-based review',
      text: [
        'This review uses Kit’s pricing page and help center as checked on 24 September 2026. Domsky has not completed the signup-to-unsubscribe product test described below. Product capabilities are attributed to Kit; plan recommendations are Domsky editorial analysis. ',
        { text: 'See how Domsky verifies software claims', href: '/methodology' },
        '.',
      ],
    },
    { type: 'heading', level: 2, id: 'short-answer', text: 'The short answer' },
    {
      type: 'quickAnswer',
      title: 'Start Free until a named automation requires Creator',
      text: 'Kit Free fits forms, landing pages, an incentive email, one-off broadcasts and simple list organization. A conventional multi-email welcome series currently requires a paid plan.',
    },
    { type: 'paragraph', text: 'Kit—formerly ConvertKit—is a practical option for a creator who needs forms, landing pages, one-off newsletters and basic subscriber organization. Its Free plan currently supports up to 10,000 subscribers.' },
    { type: 'paragraph', text: 'The important limit is workflow depth. Kit’s current Free-plan documentation excludes visual automations, email sequences and rules. You can collect subscribers, send broadcasts and deliver a file through the confirmation email, but a conventional multi-email welcome series requires a paid plan.' },
    { type: 'paragraph', text: [{ text: 'Short recommendation: ', strong: true }, 'Start with Kit Free if a form, an incentive email and manual broadcasts cover your first workflow. Choose Creator when you can name the automation you need—usually a welcome series, several lead-magnet paths or behavior-based follow-up.'] },
    { type: 'paragraph', text: ['No affiliate link is included in this review. Read the site’s ', { text: 'affiliate and editorial disclosure', href: '/disclaimer' }, ' for the policy that applies if a verified relationship is added later.'] },
    { type: 'heading', level: 2, id: 'free-plan', text: 'What Kit Free includes now' },
    { type: 'paragraph', text: 'Kit’s current pricing and Free-plan documentation list up to 10,000 email subscribers, unlimited forms and landing pages, unlimited broadcasts, tags and segments, digital products and subscriptions, broadcast A/B testing, free recommendations through the Creator Network and API access.' },
    { type: 'paragraph', text: [{ text: 'Broadcast: ', strong: true }, 'a one-off email sent at a chosen time. ', { text: 'Sequence: ', strong: true }, 'a set of automated emails a subscriber receives in order. Broadcasts are included on Free, while current Kit documentation places sequences on Creator and Pro.'] },
    {
      type: 'pricing',
      caption: 'Current documented plan boundaries',
      columns: ['Need', 'Free', 'Creator', 'Pro'],
      rows: [
        ['Forms and landing pages', 'Yes', 'Yes', 'Yes'],
        ['One-off email broadcasts', 'Yes', 'Yes', 'Yes'],
        ['Tags and segments', 'Yes', 'Yes', 'Yes'],
        ['Up to 10,000 subscribers', 'Yes', 'Paid tiers scale by list size', 'Paid tiers scale by list size'],
        ['Email sequences', 'No under current Free documentation', 'Unlimited', 'Unlimited'],
        ['Visual automations', 'No under current Free documentation', 'Unlimited', 'Unlimited'],
        ['Rules and RSS campaigns', 'No under current Free documentation', 'Yes', 'Yes'],
        ['Advanced engagement and deliverability reporting', 'No', 'Limited compared with Pro', 'Yes'],
        ['Unlimited users', 'No', 'No', 'Yes'],
      ],
    },
    { type: 'paragraph', text: [{ text: 'Official claim: ', strong: true }, 'These boundaries come from Kit’s live pricing page and current Free-plan help article.'] },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Free is a useful publishing plan, not a full automation plan. Its high subscriber ceiling should not distract from the missing workflow features.'] },
    { type: 'heading', level: 2, id: 'confirmation-vs-sequence', text: 'The important distinction: confirmation email versus welcome sequence' },
    { type: 'paragraph', text: 'Kit calls the first message attached to a form or landing page the confirmation email. It can ask the subscriber to confirm their address and can deliver a lead-magnet file after the click. That is not the same as a welcome sequence.' },
    {
      type: 'list',
      items: [
        [{ text: 'Confirmation email:', strong: true }, ' handles consent confirmation and, optionally, incentive delivery.'],
        [{ text: 'Welcome email:', strong: true }, ' introduces the newsletter or business after signup.'],
        [{ text: 'Welcome sequence:', strong: true }, ' two or more automated emails sent over time.'],
      ],
    },
    { type: 'paragraph', text: ['Kit says disabling the confirmation email also disables double opt-in. With double opt-in enabled, a subscriber must click the confirmation link before becoming confirmed. ', { text: 'Kit recommends', href: 'https://help.kit.com/en/articles/2971364-the-all-important-double-opt-in' }, ' keeping this setting on by default.'] },
    { type: 'paragraph', text: 'For a simple lead magnet, one carefully written confirmation email may be enough at the beginning. It can explain what the reader requested and take them to the file, but it should not be described as a full welcome sequence.' },
    { type: 'heading', level: 2, id: 'lead-magnet-workflow', text: 'The simple lead-magnet workflow' },
    {
      type: 'workflow',
      caption: 'Documented signup flow and current paid automation boundary',
      paths: [
        { title: 'Kit Free', steps: ['Form or landing page', 'Confirmation and double opt-in', 'Lead-magnet delivery', 'Manual broadcast'] },
        { title: 'Creator workflow', steps: ['Confirmed subscriber', 'Visual automation', 'Multi-email welcome sequence', 'Subscriber control'] },
      ],
    },
    { type: 'heading', level: 3, id: 'free-workflow', text: 'What Free can do' },
    { type: 'paragraph', text: 'On Free, you can build the form or landing page, configure the confirmation email, deliver a file through its link, organize the confirmed subscriber with tags or segments, and send future broadcasts.' },
    { type: 'paragraph', text: 'That can support a deliberately simple newsletter with one lead magnet, one audience, a clear confirmation message and a regular manual newsletter. It can also be easier to inspect than a complex automation.' },
    { type: 'heading', level: 3, id: 'creator-boundary', text: 'Where Creator becomes necessary' },
    { type: 'paragraph', text: 'Upgrade pressure appears when the workflow needs to continue automatically after confirmation. Kit documents Email Sequences as ordered sets of automated emails and Visual Automations as the flow connecting an entry point, such as a form, to actions such as sending a sequence or adding a tag.' },
    {
      type: 'list',
      items: [
        'an automated two- or three-email welcome series;',
        'different follow-up sequences for different forms;',
        'rules that react to subscriber activity;',
        'several automation paths; or',
        'an RSS-based email campaign.',
      ],
    },
    { type: 'paragraph', text: 'Do not pay for automation as an abstract benefit. Write the exact flow first. If you cannot name the second email, its delay and the reason it needs to be automatic, the paid plan may be premature.' },
    { type: 'heading', level: 2, id: 'subscriber-counting', text: 'What counts toward your subscriber limit' },
    { type: 'paragraph', text: 'Kit’s subscriber-status documentation says only confirmed subscribers count toward billing and can be emailed through Kit. This includes cold subscribers that remain confirmed.' },
    { type: 'paragraph', text: 'Unconfirmed subscribers have not completed the confirmation step. They do not count toward billing and cannot be emailed. Unsubscribed subscribers remain in the account with their historical data, but they do not count toward billing and cannot receive further Kit email.' },
    {
      type: 'list',
      ordered: true,
      items: [
        'A high raw signup count is not necessarily the same as the billable list size.',
        'A confirmed but inactive list can still push the account into a higher subscriber tier.',
      ],
    },
    { type: 'paragraph', text: 'List cleaning should be a considered editorial and data decision. Export a backup, define inactivity consistently and distinguish unsubscribing from deleting. Kit says deleting removes the subscriber and historical data, while unsubscribing retains history.' },
    { type: 'heading', level: 2, id: 'price', text: 'Price and upgrade triggers' },
    { type: 'paragraph', text: 'Kit’s public pricing page displayed these US-dollar prices for up to 1,000 subscribers when checked on 24 September 2026.' },
    {
      type: 'pricing',
      caption: 'Displayed pricing and billing cadence',
      columns: ['Plan', 'Displayed price', 'Billing note'],
      rows: [
        ['Free', '$0/month', 'Up to 10,000 subscribers under current plan terms'],
        ['Creator', '$33/month equivalent', '$390 billed yearly; page says this saves $78 per year'],
        ['Pro', '$66/month equivalent', '$790 billed yearly; page says this saves $158 per year'],
      ],
    },
    { type: 'note', title: 'Check the live checkout', text: 'A current Kit help article separately lists starting monthly prices of $39 for Creator and $79 for Pro at up to 1,000 subscribers. These figures represent a different billing cadence. Confirm subscriber tier, currency, tax, billing cadence and renewal term before paying.' },
    {
      type: 'list',
      items: [
        'a documented need for an automated welcome sequence;',
        'more than one repeatable subscriber journey;',
        'rules or RSS campaigns that remove recurring manual work;',
        'a paid integration the workflow genuinely requires; or',
        'Pro-only reporting or collaboration that affects a real operating decision.',
      ],
    },
    { type: 'paragraph', text: 'List growth alone is not a sufficient upgrade trigger while the current Free plan supports up to 10,000 subscribers.' },
    { type: 'heading', level: 2, id: 'integrations-export', text: 'Integrations, export and leaving later' },
    { type: 'paragraph', text: 'Kit lists API access on the Free plan. Its app documentation says some apps are available on Free while others display an upgrade requirement. Check the exact integration before choosing a plan.' },
    { type: 'paragraph', text: 'Kit documents CSV export for subscribers and filtered groups. A regular export provides a portable backup of the audience data the platform allows you to download.' },
    {
      type: 'list',
      items: [
        'export the full subscriber list and open the CSV;',
        'export a tagged or filtered group;',
        'unsubscribe a test address and confirm that sending stops;',
        'distinguish unsubscribe from permanent deletion;',
        'record which fields, tags and timestamps appear; and',
        'confirm how an imported contact is treated before migration.',
      ],
    },
    { type: 'paragraph', text: 'Documentation can establish that the controls exist. Only an account-level test can show whether the current interface and exported fields fit your process.' },
    { type: 'heading', level: 2, id: 'launch-tests', text: 'Practical limitations to test before launch' },
    { type: 'paragraph', text: 'This review does not claim firsthand results. These checks remain part of Domsky’s pre-publication product test and should also form the reader’s launch checklist.' },
    {
      type: 'table',
      caption: 'Signup-to-unsubscribe workflow checks',
      columns: ['Test', 'What to verify', 'Why it matters'],
      rows: [
        ['Form submission', 'Success state, mobile usability and stored fields', 'Prevents a broken first step'],
        ['Confirmation', 'Message arrives, sender is recognizable and link works', 'Confirms the consent path'],
        ['Lead-magnet delivery', 'Correct file or page appears after the click', 'Prevents a poor first impression'],
        ['Welcome flow', 'Correct message or paid sequence starts once', 'Catches duplicate or missing entry logic'],
        ['Tagging', 'Expected tag appears and no unrelated tag is added', 'Keeps later targeting reliable'],
        ['Unsubscribe', 'Test address stops receiving email', 'Checks a basic subscriber-control requirement'],
        ['Export', 'CSV opens and contains the fields you need', 'Reduces platform lock-in'],
        ['Mobile rendering', 'Form and email remain readable on a phone', 'Protects the common signup path'],
      ],
    },
    { type: 'paragraph', text: 'Email placement can vary by sender setup, domain reputation, recipient provider and message content. A successful test to one inbox does not prove universal deliverability. This article makes no inbox-placement promise.' },
    { type: 'heading', level: 2, id: 'plan-fit', text: 'Which plan fits which creator' },
    {
      type: 'table',
      caption: 'Situation-to-plan recommendation',
      columns: ['Situation', 'Start with', 'Reason'],
      rows: [
        ['New newsletter, one form, regular manual sends', 'Free', 'The included form, confirmation and broadcasts cover the workflow'],
        ['One lead magnet, no multi-email follow-up yet', 'Free', 'Use the confirmation email for delivery and add broadcasts deliberately'],
        ['Automated welcome series after signup', 'Creator', 'Current Free documentation excludes sequences and visual automations'],
        ['Several lead magnets with different follow-up paths', 'Creator', 'Multiple sequences and automation actions are the relevant value'],
        ['Team members need access and advanced reporting', 'Pro', 'Pro adds unlimited users and deeper analytics/reporting'],
        ['Newsletter-first media business comparing platforms', 'Compare first', 'Another platform may better match the operating model'],
      ],
    },
    { type: 'paragraph', text: [{ text: 'Domsky analysis: ', strong: true }, 'Most beginners should choose between Free and Creator. Pro should solve a named reporting or collaboration problem, not serve as a status upgrade.'] },
    { type: 'heading', level: 2, id: 'poor-fit', text: 'When Kit is not the best fit' },
    {
      type: 'list',
      items: [
        'an automated welcome sequence is required but the paid price is outside the budget;',
        'a required integration is unavailable or requires an unwanted upgrade;',
        'the primary product is a publication and another newsletter-site or advertising model fits better;',
        'the team needs a traditional marketing suite with broader CRM functions; or',
        'another tool’s free plan includes the exact automation being planned.',
      ],
    },
    { type: 'paragraph', text: 'Those are workflow mismatches, not evidence that Kit is generally bad. Compare the same subscriber count, billing cadence and required workflow across alternatives. The DCE-05 comparison link remains withheld until that article is live.' },
    { type: 'heading', level: 2, id: 'recommendation', text: 'Domsky recommendation' },
    {
      type: 'bestFor',
      title: 'Choose the lowest plan that runs the defined workflow',
      text: 'Choose Free for a simple list, form, incentive delivery and manual broadcasts. Choose Creator when an automated welcome sequence or multiple subscriber journeys are part of the current plan. Choose Pro only for a named collaboration or reporting requirement.',
    },
    { type: 'paragraph', text: 'The practical rule is simple: pay for the first required workflow that Free cannot run. Before committing, complete one full signup-to-unsubscribe test and export the resulting test record.' },
    { type: 'cta', title: 'Map your workflow before choosing a plan', text: 'If broadcasts and a simple incentive email are enough, start with Free. If you need a welcome sequence, verify the current Creator checkout price.', label: 'Review the workflow boundary', href: '#lead-magnet-workflow' },
    { type: 'heading', level: 2, id: 'questions', text: 'Common questions' },
    { type: 'heading', level: 3, id: 'convertkit-name', text: 'Is Kit still ConvertKit?' },
    { type: 'paragraph', text: 'Kit is the current product name; the company describes it as formerly ConvertKit. This page keeps the older /reviews/convertkit route so existing links do not need to change.' },
    { type: 'heading', level: 3, id: 'free-subscribers', text: 'Is Kit really free for up to 10,000 subscribers?' },
    { type: 'paragraph', text: 'Kit’s current Free-plan and pricing pages say yes, subject to current terms. The plan includes forms, landing pages, broadcasts, tagging and segmentation, but not every automation or app feature.' },
    { type: 'heading', level: 3, id: 'free-sequence', text: 'Can Kit Free send a welcome sequence?' },
    { type: 'paragraph', text: 'Not under Kit’s current Free-plan documentation. Email sequences and visual automations are listed as paid-plan features. Free can send a confirmation or incentive email and one-off broadcasts.' },
    { type: 'heading', level: 3, id: 'confirmation-welcome', text: 'Does the confirmation email count as a welcome email?' },
    { type: 'paragraph', text: 'It can welcome the subscriber and deliver a file, but it is primarily the confirmation and incentive step. It is not the same as a timed multi-email welcome sequence.' },
    { type: 'heading', level: 3, id: 'billing-subscribers', text: 'Which subscribers count toward billing?' },
    { type: 'paragraph', text: 'Kit says confirmed subscribers count toward billing and can be emailed. Unconfirmed and unsubscribed contacts do not count. Confirmed cold subscribers remain in the total.' },
    { type: 'heading', level: 3, id: 'export-list', text: 'Can I export my list?' },
    { type: 'paragraph', text: 'Kit documents CSV exports for the subscriber list and subsets. Test the current export before launch to confirm that it contains the fields and organization you need.' },
    { type: 'paragraph', text: 'Pricing, plan boundaries and workflow descriptions come from Kit’s official pages listed below. Domsky has not completed its controlled workflow test, so this review does not rate setup ease, delivery speed, inbox placement or support quality.' },
    { type: 'sources', id: 'sources', title: 'Sources and evidence limits' },
  ],
} satisfies ArticleDocument;

