import type { ArticleDocument } from '../types';

export const leanSoloBusinessStack = {
  id: 'dce-08-lean-solo-business-stack',
  title: 'A Lean Solo-Business Stack: What to Use, Keep and Skip',
  slug: '/uses',
  description: 'Choose a smaller software stack for writing, client work or a website. Keep useful tools, identify gaps and avoid overlapping subscriptions.',
  excerpt: 'Three practical paths for choosing the smallest useful software stack without turning every category into a purchase.',
  deck: 'Start with the work you perform every week, retain tools that already cover it and add a paid product only when a tested gap blocks current work.',
  seoTitle: 'A Lean Solo-Business Stack: Use, Keep and Skip | Domsky',
  socialTitle: 'The Lean Solo-Business Stack: Keep, Add or Skip',
  socialDescription: 'Choose a minimum stack for writing, client work or a small website—without paying twice for the same job.',
  category: 'Lean Software Stack',
  author: { name: 'Dominik', type: 'Person', url: '/about' },
  publishedAt: '2026-09-25', updatedAt: '2026-09-25', verifiedAt: '2026-09-25',
  status: 'published', contentType: 'guide',
  tags: ['Solo business', 'Software stack', 'AI assistant', 'Email marketing', 'Website builder', 'Cost control'],
  relatedSlugs: ['/blog/replaced-saas-stack-with-ai-tools', '/comparisons/claude-vs-chatgpt-vs-gemini-2026', '/blog/ai-daily-workflow-solo-business', '/reviews/convertkit'],
  readingMinutes: 14,
  featuredImageRequired: true,
  featuredImage: { src: '/images/lean-solo-business-stack.svg', alt: 'Three lean software-stack paths for a writer, service provider and small website builder', caption: 'Begin with an existing-tool check, then add only the capability a current job still needs.', width: 1600, height: 900 },
  ogImage: { src: '/images/lean-solo-business-stack.svg', alt: 'Three lean software-stack paths for a writer, service provider and small website builder', width: 1600, height: 900 },
  commercial: false,
  recommendedUpdateDays: 30,
  affiliateDisclosureRequired: false,
  disclosure: 'This guide recommends a minimum stack by business situation. Product capabilities come from current official documentation; selection guidance is Domsky editorial analysis. A recommendation does not mean Domsky uses or has tested the product. This page contains no affiliate links.',
  verificationPending: [],
  sources: [
    { id: 'kit-automation', title: 'Kit Help: Visual Automations on the Newsletter Plan', url: 'https://help.kit.com/en/articles/9053626-visual-automations-on-the-newsletter-plan' },
    { id: 'kit-newsletter', title: 'Kit Help: The Kit Newsletter Plan', url: 'https://help.kit.com/en/articles/9053602-the-kit-newsletter-plan' },
    { id: 'framer-pricing', title: 'Framer: Pricing', url: 'https://www.framer.com/pricing' },
    { id: 'framer-use-cases', title: 'Framer Help: Best use cases for each Framer plan', url: 'https://www.framer.com/help/articles/best-use-cases-for-each-framer-plan/' },
    { id: 'framer-domain', title: 'Framer Help: How to connect a custom domain', url: 'https://www.framer.com/help/articles/how-to-connect-a-custom-domain/' },
    { id: 'framer-export', title: 'Framer Help: Can I export my website to HTML and self-host it?', url: 'https://www.framer.com/help/articles/can-i-export-my-website-to-html-and-self-host-it/' },
    { id: 'framer-charges', title: 'Framer Help: Subscriptions and charges', url: 'https://www.framer.com/help/articles/subscriptions-and-charges/' },
    { id: 'finops-usage', title: 'FinOps Framework: Optimize Usage', url: 'https://www.finops.org/framework/capabilities/optimize-usage/' },
    { id: 'finops-licensing', title: 'FinOps Framework: Licensing & SaaS', url: 'https://www.finops.org/framework/capabilities/licensing-saas/' },
  ],
  blocks: [
    { type: 'note', title: 'Evidence and recommendation disclosure', text: 'This page uses provider documentation for product facts and labels scenario choices as Domsky editorial analysis. It does not claim that Domsky currently uses the named products. A public “What Domsky uses” section requires an owner-approved current-use record and evidence date.' },
    { type: 'quickAnswer', title: 'Quick answer', text: 'The smallest useful stack starts with jobs performed every week. Keep existing tools that complete those jobs, identify one uncovered requirement, trial a candidate against that requirement and count only its incremental recurring cost. Skip categories that solve no current task.' },
    { type: 'paragraph', text: 'A writer needs a reliable place to research, draft and edit. A service provider first needs to deliver work and communicate with clients. A small-site builder needs a maintainable publishing path. Buying the same ten tools for all three situations creates cost and complexity before it creates value.' },
    { type: 'list', ordered: true, items: ['What work do you perform every week?', 'Which tools you already have complete that work well enough?', 'What specific capability is still missing?'] },
    { type: 'paragraph', text: ['If you cannot name the missing capability, do not add a subscription yet. If AI is new to you, ', { text: 'start with three practical AI tasks', href: '/blog/you-dont-need-to-be-technical-to-use-ai' }, ' before choosing a paid plan.'] },

    { type: 'heading', level: 2, id: 'work-first', text: 'Start with the work, not the tool list' },
    { type: 'paragraph', text: 'A software category becomes necessary only when it serves a current job. Use outcomes such as drafting one useful article, delivering client work, publishing five website pages, collecting subscribers with consent or tracking renewals.' },
    { type: 'table', caption: 'Classify the current setup before researching a product', columns: ['Status', 'Meaning', 'Decision'], rows: [
      ['Covered', 'An existing tool completes the job reliably', 'Keep the existing path'],
      ['Partly covered', 'The job works, but a repeated limitation is visible', 'Define and test the gap'],
      ['Not covered', 'A required step cannot be completed', 'Trial one candidate'],
      ['Not needed yet', 'The job is not part of the current business', 'Skip the category'],
    ] },
    { type: 'paragraph', text: 'Avoid vague requirements such as “do marketing,” “use AI” or “automate the business.” Those phrases make almost every product look necessary. Only a partly covered or uncovered current job justifies researching another tool.' },

    { type: 'heading', level: 2, id: 'rules', text: 'The three lean-stack rules' },
    { type: 'heading', level: 3, id: 'existing-wins', text: '1. Existing sufficient access wins' },
    { type: 'paragraph', text: 'If an editor, calendar, file store or website platform already performs the required job, keep it until a documented limitation appears. Familiarity and preserved data have value even when another product has more features.' },
    { type: 'heading', level: 3, id: 'one-assistant', text: '2. One paid general assistant is enough to start' },
    { type: 'paragraph', text: ['ChatGPT, Claude and Gemini overlap across writing, files, research and connected work. ', { text: 'Choose one general assistant by recurring task', href: '/comparisons/claude-vs-chatgpt-vs-gemini-2026' }, ' and pay only when its paid plan removes a repeated bottleneck. A second paid assistant needs a separate recurring job and evidence that the first cannot cover it well enough.'] },
    { type: 'heading', level: 3, id: 'skip-category', text: '3. A category can be skipped' },
    { type: 'paragraph', text: 'You do not need email software before you intend to contact subscribers, automation before a manual process repeats often enough to measure, or another design subscription when an existing editor covers the required output. Skipping is an active decision.' },

    { type: 'heading', level: 2, id: 'situations', text: 'Choose by situation' },
    { type: 'table', caption: 'Minimum-stack scenario matrix', columns: ['Current job', 'Existing-tool option', 'Missing capability', 'Candidate only if needed', 'Upgrade trigger', 'Skip condition'], rows: [
      ['Writer publishing articles', 'Current document editor', 'Repeated research or drafting help', 'One assistant selected by task', 'Free access repeatedly blocks work', 'Occasional work fits current access'],
      ['Writer building an audience', 'Editor and manual publishing', 'Consent-based subscriber capture and email', 'Kit Newsletter Plan is one candidate', 'More journeys or advanced automation are required', 'No current plan to email readers'],
      ['Service provider delivering work', 'Current email, calendar, documents and delivery tools', 'Only the observed missing step', 'Research after the gap is measured', 'Repeated delay or error exceeds switching cost', 'Current workflow is dependable'],
      ['Small site using a visual workflow', 'Current site platform', 'Maintain pages on a chosen domain', 'Framer is one visual-builder candidate', 'Domain, CMS or collaboration needs exceed current plan', 'Existing site is maintainable'],
      ['Small site maintaining code', 'Repository, editor and deployment path', 'Safe preview, rollback and domain connection', 'Choose only after a maintenance test', 'Current path cannot be maintained safely', 'Existing supervised path works'],
    ] },
    { type: 'paragraph', text: ['Each row is a separate situation; it is not a universal bundle. For a faster task-based result, use the ', { text: 'Lean Stack Finder', href: '/#stack-finder' }, ', which applies the same existing-access, current-job, trial and skip rules.'] },

    { type: 'heading', level: 2, id: 'writer', text: 'A lean setup for a writer' },
    { type: 'decisionCards', cards: [
      { label: 'Keep', title: 'The reliable writing path', text: 'Keep the document editor, browser, source-capture method and one assistant that already support recurring work.' },
      { label: 'Add', title: 'One measured missing capability', text: 'Consider email, specialized research or scheduling only when a current workflow has a repeated documented gap.' },
      { label: 'Skip', title: 'Duplicate subscriptions', text: 'Skip a second general assistant, overlapping rewriting tools, premature social automation and unnecessary design software.' },
    ] },
    { type: 'paragraph', text: ['The minimum writer path can be an editor plus free assistant access. ', { text: 'Follow the lean content workflow', href: '/blog/ai-daily-workflow-solo-business' }, ' before expanding the stack: define one reader question, build the evidence ledger, approve the article and then adapt it.'] },
    { type: 'heading', level: 3, id: 'writer-email', text: 'When email becomes useful' },
    { type: 'paragraph', text: 'Email software is justified when you can name what readers subscribe to, the consent and confirmation flow, the first email or sequence, the sending plan and how contacts and exports will be maintained.' },
    { type: 'paragraph', text: ['Kit is one candidate, not a default. As checked on 25 September 2026, its Newsletter Plan supports one Email Sequence and one basic Visual Automation. Paid plans become relevant when the workflow needs more or more advanced automation. ', { text: 'Check Kit’s current limits and upgrade triggers', href: '/reviews/convertkit' }, ' before implementation.'] },

    { type: 'heading', level: 2, id: 'service-provider', text: 'A lean setup for a service provider' },
    { type: 'paragraph', text: 'Start with one complete delivery path: inquiry, scope, meeting or access, work, delivery, payment record and follow-up. Keep existing email, calendar, documents, file delivery and billing methods when they are dependable and appropriate.' },
    { type: 'list', items: ['Inquiries are repeatedly lost.', 'The same scheduling exchange consumes significant time.', 'Required approvals are not recorded.', 'File versions become confused.', 'Renewal or follow-up dates are missed.'] },
    { type: 'paragraph', text: 'These are measurable gaps worth investigating. Research one capability at a time. A CRM, scheduler, automation platform and proposal suite are not automatic starter requirements. An assistant should not receive confidential client information unless the provider’s controls and the business’s obligations allow it.' },

    { type: 'heading', level: 2, id: 'small-website', text: 'A lean setup for a small website' },
    { type: 'paragraph', text: 'The important choice is which publishing path can be maintained safely after launch.' },
    { type: 'table', caption: 'Visual builder or supervised code?', columns: ['Decision factor', 'Visual-builder path', 'Supervised-code path'], rows: [
      ['Best fit', 'A visual canvas and managed publishing are preferred', 'A repository can be maintained or reliable technical help exists'],
      ['Main advantage', 'Layout, CMS and publishing in one interface', 'Control over implementation and deployment workflow'],
      ['Main dependency', 'Platform plan, hosting model and transfer rules', 'Code quality, dependencies, deployment and rollback knowledge'],
      ['Required test', 'Edit, publish, connect domain, restore and hand off', 'Clone, preview, deploy, roll back and update dependencies'],
      ['Skip when', 'The existing platform is already sufficient', 'No one can maintain the code path safely'],
    ] },
    { type: 'heading', level: 3, id: 'visual-builder', text: 'Visual-builder path' },
    { type: 'paragraph', text: 'Framer is one candidate for a visually managed site. Its current Free plan is described for hobby or personal projects on a Framer subdomain. Connecting a custom domain and running a business site requires checking the current paid Site plans, limits and billing basis.' },
    { type: 'paragraph', text: 'Framer publishes through its own hosting model; conventional static HTML export for independent self-hosting is not the default path. That does not make it a poor choice, but you should accept the hosting and migration model before building the site.' },
    { type: 'list', items: ['Test page editing and mobile layout.', 'Check CMS needs, item limits, forms and integrations.', 'Test custom-domain connection, redirects and SEO controls.', 'Check backup, version recovery and ownership transfer.', 'Confirm what can be exported if the platform changes.'] },
    { type: 'heading', level: 3, id: 'supervised-code', text: 'Supervised-code path' },
    { type: 'paragraph', text: 'A code-maintained site can be lean when an owner or reliable collaborator understands the content and configuration, can preview and roll back changes, keeps secrets outside public code, maintains dependencies and owns the domain and hosting connection.' },
    { type: 'paragraph', text: '“AI can generate the code” is not enough when those responsibilities are unclear. Generation and maintenance are different jobs. Add another coding assistant, CMS or monitoring product only when a recurring maintenance problem is documented.' },
    { type: 'heading', level: 3, id: 'domain-costs', text: 'Domain and renewal costs' },
    { type: 'paragraph', text: 'Treat a custom domain as a separate asset. Record its provider, owner account, recovery method, introductory price, standard renewal price, renewal date, transfer conditions and DNS dependency. Never present a first-year promotion as the permanent annual cost.' },

    { type: 'heading', level: 2, id: 'keep-add-skip', text: 'What to keep, add or skip' },
    { type: 'table', caption: 'Category decision matrix', columns: ['Category', 'Keep when', 'Add when', 'Skip when'], rows: [
      ['General AI assistant', 'It supports recurring tasks within acceptable limits', 'A free limit or paid feature repeatedly blocks work', 'Tasks are occasional or current access is enough'],
      ['Second paid assistant', 'It has a separate tested job with incremental value', 'The first cannot cover that documented job', 'It mostly duplicates drafting, files or research'],
      ['Email platform', 'A list and sending workflow already exist', 'Subscriber capture and planned email require it', 'No email-audience workflow exists'],
      ['Automation', 'A repeated stable process is understood', 'Manual repetition causes measurable errors or delay', 'The process is rare or still changing'],
      ['Design tool', 'It produces required assets not covered elsewhere', 'Recurring output needs its unique capability', 'An existing editor or builder covers the task'],
      ['Scheduler', 'Approved content across channels needs coordination', 'Manual scheduling is a documented bottleneck', 'Content volume is low'],
      ['CRM or client platform', 'It prevents loss across a real pipeline', 'Current records fail at a defined step', 'A simple dependable system covers the load'],
      ['Website builder or host', 'The site is maintainable and meets current needs', 'A real publishing or maintenance gap exists', 'The existing path is sufficient'],
    ] },
    { type: 'paragraph', text: '“Add” is a research trigger, not an instruction to purchase the first candidate.' },

    { type: 'heading', level: 2, id: 'cost', text: 'Review the cost before adding anything' },
    { type: 'quote', text: 'Recurring net change = new recurring costs − recurring costs actually removed' },
    { type: 'paragraph', text: ['Use the ', { text: 'software stack audit', href: '/blog/replaced-saas-stack-with-ai-tools' }, ' for every proposed addition. Record one-time migration cash and owner time separately. Existing access is not incremental spend, while a new assistant that replaces no subscription is fully incremental.'] },
    { type: 'paragraph', text: 'Avoid a universal “complete stack” total. Readers begin with different access, currencies, taxes, renewal dates and needs. If a website plan replaces hosting, show both the removed and added costs; if a domain offer covers only the first year, record the later renewal separately.' },
    { type: 'cta', title: 'Audit what you already have', text: 'Map every subscription to a required job, test replacement coverage and calculate recurring cash without hiding migration cost or owner time.', label: 'Open the software stack audit', href: '/blog/replaced-saas-stack-with-ai-tools' },

    { type: 'heading', level: 2, id: 'five-questions', text: 'A five-question stack check' },
    { type: 'list', ordered: true, items: ['What current job is blocked? Name the exact output or failure.', 'Can an existing tool cover it? Test current entitlement and configuration first.', 'What must a candidate prove? Define pass/fail criteria with non-critical work.', 'What is the incremental cost? Include the billing commitment and retained tools.', 'What can be skipped or removed? Do not call a tool a replacement before coverage and migration are verified.'] },

    { type: 'heading', level: 2, id: 'questions', text: 'Common questions' },
    { type: 'heading', level: 3, id: 'paid-every-category', text: 'Do I need a paid tool in every category?' },
    { type: 'paragraph', text: 'No. Most starter scenarios need only a few capabilities, and existing or free access may cover them. A category belongs in the stack only when it performs a current job.' },
    { type: 'heading', level: 3, id: 'two-assistants', text: 'Should I pay for more than one AI assistant?' },
    { type: 'paragraph', text: 'Usually not at the start. Choose one by recurring task, workflow fit and existing ecosystem. Add a second paid assistant only when it proves a separate benefit that justifies the full incremental cost.' },
    { type: 'heading', level: 3, id: 'email-immediately', text: 'Do I need email software immediately?' },
    { type: 'paragraph', text: 'Only when you plan to collect subscribers and send useful email with defined consent, confirmation and maintenance. Building an empty automation is not progress.' },
    { type: 'heading', level: 3, id: 'builder-or-code', text: 'Is a visual builder or code path better?' },
    { type: 'paragraph', text: 'Choose the path you can maintain. A visual builder reduces code responsibility but introduces platform-plan and portability considerations. A code path offers control but requires safe updates, deployment and rollback.' },
    { type: 'heading', level: 3, id: 'domsky-use', text: 'Is a tool Domsky uses automatically right for me?' },
    { type: 'paragraph', text: 'No. Documented use describes Domsky’s workflow; a recommendation explains who a product may fit. Neither is a universal instruction. This page omits a “What Domsky uses” section because the package contains no owner-approved current-use record.' },

    { type: 'heading', level: 2, id: 'evidence-policy', text: 'Evidence and recommendation policy' },
    { type: 'table', caption: 'How to read claims on this page', columns: ['Statement type', 'Meaning'], rows: [
      ['Provider fact', 'A current feature, limit or billing rule documented by the provider'],
      ['Domsky recommendation', 'A conditional editorial judgment based on the reader’s scenario'],
      ['Documented use', 'A current named purpose supported by an approved use record and date'],
      ['Illustrative example', 'A teaching scenario that is not a claim about a reader or Domsky'],
    ] },
    { type: 'paragraph', text: 'No affiliate relationship changes these labels. Commercial links, if approved later, belong after the keep-or-skip decision and require clear disclosure. Keep what works, add the smallest missing capability and skip the rest until the work changes.' },
    { type: 'sources', id: 'sources', title: 'Sources and further reading' },
  ],
} satisfies ArticleDocument;
