import type { ArticleDocument } from '../types';
import { PUBLIC_AUTHOR } from '../../data/site';

export const leanContentWorkflow = {
  id: 'dce-06-lean-content-workflow',
  title: 'A Lean Content Workflow: Turn One Researched Idea into an Article, Email and Social Post',
  slug: '/blog/ai-daily-workflow-solo-business',
  description: 'Turn one researched idea into an article, email and social post using one assistant, a source ledger and clear human review steps.',
  excerpt: 'A documented seven-step workflow for turning one verified idea into three useful formats without spreading unsupported claims.',
  deck: 'Lock the reader question and evidence first, approve the article, then adapt only its supported claims for email and social.',
  seoTitle: 'A Lean AI Content Workflow for Solo Creators | Domsky',
  socialTitle: 'One Research Idea, Three Approved Content Assets',
  socialDescription: 'Use a source ledger and two human approval gates to create an article, email and social post without spreading unsupported claims.',
  category: 'Workflows',
  author: PUBLIC_AUTHOR,
  publishedAt: '2026-09-25',
  updatedAt: '2026-09-25',
  verifiedAt: '2026-09-25',
  status: 'published',
  contentType: 'guide',
  tags: ['Content workflow', 'AI assistants', 'Editorial review', 'Source verification', 'Solo creators'],
  relatedSlugs: [
    '/uses',
    '/comparisons/kit-vs-mailerlite-vs-beehiiv',
    '/comparisons/claude-vs-chatgpt-vs-gemini-2026',
    '/reviews/convertkit',
  ],
  readingMinutes: 15,
  featuredImageRequired: true,
  featuredImage: {
    src: '/images/lean-content-workflow.svg',
    alt: 'A source ledger flowing through human review into an article, email and LinkedIn post.',
    caption: 'One researched idea becomes three purpose-specific assets, with human approval before drafting and release.',
    width: 1600,
    height: 900,
  },
  ogImage: {
    src: '/images/lean-content-workflow.svg',
    alt: 'One researched idea flowing into an article, email and social post.',
    width: 1600,
    height: 900,
  },
  commercial: false,
  recommendedUpdateDays: 30,
  affiliateDisclosureRequired: false,
  disclosure: 'This tutorial contains no affiliate links. Product references support the documented example and do not determine the editorial recommendation.',
  verificationPending: [],
  sources: [
    { id: 'kit-01', title: 'Kit Help Center: Visual Automations on the Newsletter Plan', url: 'https://help.kit.com/en/articles/9053626-visual-automations-on-the-newsletter-plan' },
    { id: 'kit-02', title: 'Kit Help Center: How to use Kit Visual Automations', url: 'https://help.kit.com/en/articles/2502666-how-to-use-kit-visual-automations' },
    { id: 'ml-01', title: 'MailerLite Help: Free plan update', url: 'https://www.mailerlite.com/help/free-plan-update-faq' },
    { id: 'ml-02', title: 'MailerLite: Pricing and plan comparison', url: 'https://www.mailerlite.com/pricing' },
    { id: 'bh-01', title: 'beehiiv Help: Welcome email vs welcome automation', url: 'https://www.beehiiv.com/support/article/38813477234071-welcome-email-vs-welcome-automation-which-should-you-use' },
    { id: 'li-01', title: 'LinkedIn Help: Post and share updates', url: 'https://www.linkedin.com/help/linkedin/answer/a528176' },
  ],
  blocks: [
    {
      type: 'note',
      title: 'Documented editorial demonstration',
      text: [
        'This tutorial includes a documented example prepared on 25 September 2026 from current official product documentation. The example produced draft assets, but they were not emailed, posted or measured for performance. Product facts are attributed to their providers; the workflow recommendations are Domsky editorial analysis. ',
        { text: 'See how Domsky verifies software claims', href: '/methodology' },
        '.',
      ],
    },
    { type: 'paragraph', text: 'You do not need a different AI tool for research, writing, email and social media.' },
    { type: 'paragraph', text: 'You need a controlled sequence of decisions:' },
    {
      type: 'workflow',
      caption: 'The seven-stage editorial sequence',
      paths: [{
        title: 'One researched idea',
        steps: ['Define the question', 'Build the source ledger', 'Approve the argument', 'Draft with claim references', 'Correct and approve', 'Adapt for each format', 'Run the release check'],
      }],
    },
    { type: 'paragraph', text: 'The order matters. If you create every asset from an unverified idea, one weak claim spreads into three places. If you approve the evidence and article first, the derivatives inherit a stable factual core.' },
    { type: 'paragraph', text: 'This guide demonstrates the process with one narrow question: Does a free email plan include the welcome sequence a beginner expects?' },
    { type: 'paragraph', text: ['The finished outputs are a compact article, an email and a LinkedIn post. No automation or extra design subscription is required. When choosing the assistant, ', { text: 'compare one assistant for your workflow', href: '/comparisons/claude-vs-chatgpt-vs-gemini-2026' }, ' instead of assembling a large overlapping stack.'] },
    { type: 'heading', level: 2, id: 'workflow', text: 'The workflow in one view' },
    {
      type: 'table',
      caption: 'Inputs, outputs and approval evidence for each stage',
      columns: ['Stage', 'Input', 'Output', 'Human check', 'Evidence retained'],
      rows: [
        ['1. Brief', 'Audience and one question', 'Scope and three formats', 'Is the question useful and narrow?', 'Approved brief'],
        ['2. Research', 'Official sources', 'Source ledger and claim list', 'Does each claim have direct support?', 'URLs, dates and notes'],
        ['3. Argument', 'Claim list', 'Thesis, outline and exclusions', 'Is this the position Domsky wants to take?', 'Approved outline'],
        ['4. Article draft', 'Approved outline and ledger', 'Draft with source IDs', 'Are facts separated from analysis?', 'Versioned draft'],
        ['5. Review', 'Draft and sources', 'Corrected approved article', 'Any stale facts or unsupported certainty?', 'Correction log'],
        ['6. Adapt', 'Approved article', 'Email and LinkedIn post', 'Is each useful in its own context?', 'Derivative drafts'],
        ['7. Release check', 'All assets', 'Ready-to-schedule package', 'Are links, facts and formats correct?', 'Checklist and dates'],
      ],
    },
    { type: 'paragraph', text: 'The assistant can help organize, draft and compress. The editor still chooses the question, approves the conclusion and decides what is safe to publish.' },
    { type: 'paragraph', text: ['For the tools around this process, see the ', { text: 'wider lean stack', href: '/uses' }, ' and add a category only when the workflow exposes a real gap.'] },
    { type: 'heading', level: 2, id: 'define', text: 'Step 1 — Define one reader question and three outputs' },
    { type: 'paragraph', text: 'Avoid prompts such as “make content about email tools.” They leave the assistant to decide the audience, scope, angle and facts.' },
    {
      type: 'note',
      title: 'Bounded brief',
      text: [
        { text: 'Reader: ', strong: true }, 'beginner creator choosing a free email plan. ',
        { text: 'Question: ', strong: true }, 'does the free plan include a multi-email welcome sequence? ',
        { text: 'Decision: ', strong: true }, 'start free, choose a paid plan or simplify the workflow. ',
        { text: 'Outputs: ', strong: true }, '600-word article, subscriber email and LinkedIn post. ',
        { text: 'Evidence: ', strong: true }, 'current official provider documentation. ',
        { text: 'Exclude: ', strong: true }, 'deliverability rankings, conversion claims and a universal winner.',
      ],
    },
    { type: 'paragraph', text: ['Use the site’s ', { text: 'Prompt Builder to structure a bounded prompt', href: '/tools/prompt-builder' }, ' after the audience, question and exclusions are decided.'] },
    { type: 'paragraph', text: 'Three formats do not mean three independent arguments. The article explains the decision and preserves the evidence. The email surfaces one useful insight and sends the reader to the article. The LinkedIn post presents a self-contained observation rather than copying the article.' },
    { type: 'heading', level: 2, id: 'source-ledger', text: 'Step 2 — Build a source ledger before drafting' },
    { type: 'paragraph', text: 'A source ledger is a small table connecting each publishable claim to the page that supports it.' },
    {
      type: 'table',
      caption: 'Source ledger retained from the worked example',
      columns: ['Claim ID', 'Draft claim', 'Primary source', 'Checked', 'Confidence / limitation'],
      rows: [
        ['EX-C01', 'Kit Newsletter Plan includes one sequence and one basic visual automation', 'Kit Help: Visual Automations on the Newsletter Plan', '2026-09-25', 'Official and specific; pricing presentation is less clear'],
        ['EX-C02', 'MailerLite Free allows 250 active subscribers, 2,500 monthly sends and three automations', 'MailerLite Free-plan update and pricing', '2026-09-25', 'Official; exceeding limits pauses relevant activity'],
        ['EX-C03', 'beehiiv has one welcome email on all plans; multi-step automation is paid', 'beehiiv Help: welcome email vs welcome automation', '2026-09-25', 'Official; not a delivery-performance claim'],
        ['EX-C04', 'LinkedIn posts currently allow 3,000 characters', 'LinkedIn Help', '2026-09-25', 'Official format limit; may change'],
      ],
    },
    { type: 'paragraph', text: 'The ledger should contain only claims the article needs. Do not collect dozens of sources because they are available.' },
    {
      type: 'list',
      items: [
        'Is the sentence a fact, an official product claim, an external report or editorial analysis?',
        'Does the source directly support the sentence?',
        'Is the source current enough for the risk?',
        'Does another official page conflict with it?',
        'What would make the claim expire?',
      ],
    },
    { type: 'paragraph', text: 'If the source does not answer the exact question, narrow the sentence or leave it out.' },
    { type: 'heading', level: 2, id: 'argument', text: 'Step 3 — Approve the argument and boundaries' },
    { type: 'paragraph', text: 'Research provides facts. It does not choose the editorial conclusion.' },
    { type: 'quote', text: '“Free” does not tell you whether the plan fits. Map the required welcome workflow, then compare the exact sequence and automation limits.' },
    {
      type: 'list',
      items: [
        'Do not rank deliverability without a controlled test.',
        'Do not infer ease of use from a feature table.',
        'Do not add a universal winner.',
        'Do not turn the workflow tutorial into a product comparison.',
        'Do not add productivity or time-saving claims without a log.',
      ],
    },
    { type: 'note', title: 'Outline approval prompt', text: 'Using only the supplied claim ledger, propose an outline that answers the reader question. Separate provider claims from editorial analysis, identify unresolved conflicts and list claims the draft must not make. Do not draft the article yet.' },
    { type: 'heading', level: 2, id: 'draft', text: 'Step 4 — Draft the article with source IDs' },
    { type: 'paragraph', text: 'Draft only after the argument is approved. Keep claim IDs beside factual sentences until the evidence review is complete.' },
    { type: 'note', title: 'Drafting prompt', text: 'Draft the approved outline using only claims in the ledger. Add the relevant source ID after each factual sentence. Label editorial analysis. Preserve the exclusions and mark any missing evidence instead of filling gaps from memory.' },
    { type: 'heading', level: 3, id: 'demonstration-article', text: 'Demonstration article' },
    { type: 'paragraph', text: 'A free email plan can support a lead magnet without supporting every welcome workflow.' },
    { type: 'paragraph', text: 'One welcome email, a fixed sequence and a branching automation are different requirements. Current provider documentation shows three different boundaries.' },
    {
      type: 'list',
      items: [
        'Kit’s free Newsletter Plan includes one Email Sequence and one basic action-only Visual Automation. Paid plans add unlimited sequences and advanced automation.',
        'MailerLite Free includes three active automations, but its current limits are 250 active subscribers and 2,500 monthly sends.',
        'beehiiv provides one standalone welcome email on all plans; multi-step welcome automations require a paid plan.',
      ],
    },
    { type: 'paragraph', text: 'These facts do not identify a universal winner. They show why the required journey should be written before comparing subscriber allowances or prices.' },
    { type: 'paragraph', text: ['For the full decision context, ', { text: 'compare email plans by workflow', href: '/comparisons/kit-vs-mailerlite-vs-beehiiv' }, '. If Kit is already the likely choice, ', { text: 'check Kit’s current workflow limits', href: '/reviews/convertkit' }, '.'] },
    { type: 'heading', level: 2, id: 'review', text: 'Step 5 — Run an evidence and usefulness review' },
    { type: 'heading', level: 3, id: 'evidence-pass', text: 'Evidence pass' },
    { type: 'list', items: ['Open every cited page.', 'Check that the sentence matches the source’s scope and plan.', 'Search for a more specific or newer official page.', 'Resolve conflicts before removing claim IDs.', 'Replace broad wording with the narrow supported claim.', 'Remove claim IDs only after approval.'] },
    { type: 'heading', level: 3, id: 'usefulness-pass', text: 'Usefulness pass' },
    { type: 'list', items: ['Does the introduction explain why the reader should care?', 'Does each section support the decision?', 'Is advice distinct from vendor documentation?', 'Can a beginner understand every term?', 'Does the article say what not to do?', 'Is the next action concrete?'] },
    { type: 'heading', level: 3, id: 'voice-pass', text: 'Voice pass' },
    { type: 'list', items: ['Remove sales language and false urgency.', 'Replace generic AI phrases with specific decisions.', 'Vary sentence structure without adding decoration.', 'Keep the strongest caveat beside the claim it limits.', 'Do not pretend the writer used a product when the evidence is documentation.'] },
    { type: 'heading', level: 2, id: 'correction', text: 'Worked correction — what changed and why' },
    { type: 'paragraph', text: 'The demonstration found a real source conflict.' },
    {
      type: 'table',
      caption: 'Correction record retained from the demonstration',
      columns: ['Working draft', 'Evidence found', 'Corrected version', 'Downstream impact'],
      rows: [
        ['Kit Free does not include sequences or visual automation.', 'Kit’s updated Newsletter Plan help article includes one Email Sequence and one basic Visual Automation.', 'Kit Free includes one sequence and one basic action-only automation; paid plans add unlimited sequences and advanced automation.', 'DCE-05 and Kit free-plan summaries require correction.'],
        ['beehiiv Free cannot automate a welcome.', 'Official help distinguishes one automatic welcome email from multi-step Automations.', 'Launch can send one welcome email; multi-step flows require a paid plan.', 'Keep welcome email and welcome automation separate.'],
        ['MailerLite Free includes automation.', 'Correct but incomplete: limits are three automations, 250 active subscribers and 2,500 sends.', 'State all three boundaries together.', 'Avoid a misleading feature-only recommendation.'],
      ],
    },
    { type: 'paragraph', text: 'The lesson is not that documentation is always consistent. A claim must remain attached to the most specific current source, and conflicts must be visible instead of averaged into a confident sentence.' },
    { type: 'heading', level: 2, id: 'adapt', text: 'Step 6 — Adapt the approved article' },
    { type: 'paragraph', text: 'Do not paste the article into every channel. Preserve the approved facts but change the purpose, opening and call to action.' },
    { type: 'heading', level: 3, id: 'email', text: 'Email adaptation' },
    { type: 'paragraph', text: [{ text: 'Subject: ', strong: true }, 'Does your free email plan include the sequence you need?'] },
    { type: 'paragraph', text: [{ text: 'Preview text: ', strong: true }, '“Free” describes the price, not the workflow.'] },
    { type: 'quote', text: 'Choosing an email platform by subscriber allowance alone can hide the limit that matters most. One welcome email is not the same as a multi-email sequence, and a fixed sequence is not the same as a branching automation.' },
    { type: 'paragraph', text: 'The useful question is not “Which free plan gives me the most?” It is “What must happen after someone subscribes?” Map that journey first. Then check sequence, subscriber and send limits before building the form.' },
    { type: 'paragraph', text: 'Before sending, replace the CTA with a verified canonical link, add the required footer and disclosure, and test the message in the selected email platform. This draft is not authorization to send it.' },
    { type: 'heading', level: 3, id: 'linkedin', text: 'LinkedIn adaptation' },
    { type: 'paragraph', text: 'LinkedIn currently documents a 3,000-character limit. The demonstration stays below it and works as a self-contained observation rather than a clipped article introduction.' },
    { type: 'quote', text: '“Free plan” is not a useful email-platform requirement. The real question is what must happen after someone subscribes: one welcome email, a fixed multi-email sequence, or a branching automation based on behavior?' },
    { type: 'paragraph', text: 'The post then gives the three documented plan boundaries, the subscriber-journey checklist and the instruction to choose the lowest plan that completes it. Before publishing, replace the placeholder article URL, recheck every plan fact and keep hashtags limited to those the editor considers useful.' },
    { type: 'heading', level: 2, id: 'release-check', text: 'Step 7 — Run format-specific checks and schedule manually' },
    { type: 'heading', level: 3, id: 'article-check', text: 'Article check' },
    { type: 'list', items: ['H1, title tag and meta description match the search intent.', 'Sources support each factual claim.', 'Internal links point to ready pages.', 'Tables work on mobile and have headers.', 'Disclosure, author and dates are accurate.', 'Featured image and alt text are present.'] },
    { type: 'heading', level: 3, id: 'email-check', text: 'Email check' },
    { type: 'list', items: ['Subject and preview text work together.', 'One primary action is clear.', 'Every link uses the intended destination.', 'Required sender details, unsubscribe and disclosure are present.', 'A test email renders correctly.', 'No unsupported personalization or performance promise was introduced.'] },
    { type: 'heading', level: 3, id: 'linkedin-check', text: 'LinkedIn check' },
    { type: 'list', items: ['The post makes sense without clicking.', 'It stays within the current format limit.', 'Line breaks remain readable on mobile.', 'Claims match the approved article.', 'The placeholder URL is replaced.', 'No automated posting occurs without separate authorization.'] },
    { type: 'paragraph', text: ['Manual publishing is acceptable. Use the ', { text: 'Content Calendar to plan the next publishing date', href: '/tools/content-calendar' }, ' after the assets pass review. Automation becomes useful only when the same approved handoff creates a measurable bottleneck.'] },
    { type: 'heading', level: 2, id: 'tools', text: 'Review the workflow before adding tools' },
    { type: 'list', items: ['one assistant for organization, drafting and adaptation;', 'one document editor for approval and version history;', 'a browser for primary-source verification;', 'the website repository for the article;', 'an email platform only when there is a real list; and', 'the native social platform for final posting.'] },
    { type: 'paragraph', text: 'Do not add an automation platform merely to move an unapproved draft between tools. The slow step should be editorial judgment, not copying text.' },
    { type: 'paragraph', text: 'When a repeated bottleneck appears, document the repeated action, its frequency, the error it creates, the review that must remain manual and whether automation would reduce work without removing the approval gate.' },
    { type: 'cta', title: 'Plan your next researched piece', text: 'Choose one reader question, record the sources and schedule the next reviewable publishing package.', label: 'Open the Content Calendar', href: '/tools/content-calendar' },
    { type: 'heading', level: 2, id: 'questions', text: 'Common questions' },
    { type: 'heading', level: 3, id: 'research-first', text: 'Should research finish before drafting?' },
    { type: 'paragraph', text: 'Finish the evidence needed for the approved scope. New questions may appear during drafting, but they should return to research as explicit gaps rather than being answered from memory.' },
    { type: 'heading', level: 3, id: 'reuse-copy', text: 'Can I reuse the same text in the email and LinkedIn post?' },
    { type: 'paragraph', text: 'Reuse approved facts and the core conclusion. Rewrite the opening, structure and action for each context. Identical copy usually ignores why the reader encountered it.' },
    { type: 'heading', level: 3, id: 'automation-tool', text: 'Do I need an automation tool?' },
    { type: 'paragraph', text: 'No. A solo publisher can run this workflow with one assistant, an editor and manual publishing. Add automation after a repeated, measurable handoff problem appears.' },
    { type: 'heading', level: 3, id: 'source-conflict', text: 'What if official sources disagree?' },
    { type: 'paragraph', text: 'Prefer the most specific and current documentation, record the conflict and narrow the claim. If the conflict changes a buying decision, verify inside the product or with the provider before publishing a definitive recommendation.' },
    { type: 'heading', level: 2, id: 'limitations', text: 'Evidence and limitations' },
    { type: 'paragraph', text: 'The example assets in this article were created as one documented editorial run. They demonstrate the process and one real correction. They do not establish average time savings, output quality across topics, social reach, email engagement or product usability.' },
    { type: 'paragraph', text: 'The email and LinkedIn post are drafts. They were not sent or posted. Product facts and platform limits should be rechecked before publication, and distribution requires a separate authorized action.' },
    { type: 'sources', id: 'sources', title: 'Official sources' },
  ],
} satisfies ArticleDocument;
